Create fileRepository schema
openMetadataInitiative/openMINDS_core pull request #102
Opened 2020-10-22 15:03 UTC by skoehnen

2020-10-22 16:51 UTC, lzehl requested changes

2020-10-22 16:51 UTC, lzehl commented on v3.0/products/fileRepository.schema.json
> +      "description": "Type of media stored in this repository.",
"Media type (mime type) of this repository."

2020-10-22 16:51 UTC, lzehl commented on v3.0/products/fileRepository.schema.json
> +      "description": "Hosting provider for this repository.",
"Hosting institution/organization for this repository"

2020-10-22 16:51 UTC, lzehl commented on v3.0/products/fileRepository.schema.json
> +      "description": "Hosting provider for this repository.",
I originally thought that this is a controlledTerm with values like "EBRAINS", "GitHub" etc. but it actually should reference to an organization which all of these are. I'm sorry that I just realized this now

2020-10-22 16:51 UTC, lzehl commented on v3.0/products/fileRepository.schema.json
> +      "$ref": "https://raw.githubusercontent.com/HumanBrainProject/openMINDS/master/v3.0/definitions.json#definitions/CONTROLLED_TERM"
change to ref to organization.schema.json

2020-10-23 07:57 UTC, skoehnen commented on v3.0/products/fileRepository.schema.json
> +      "$ref": "https://raw.githubusercontent.com/HumanBrainProject/openMINDS/master/v3.0/definitions.json#definitions/CONTROLLED_TERM"
Fixed 👍

2020-10-23 07:58 UTC, skoehnen commented on v3.0/products/fileRepository.schema.json
> +      "description": "Hosting provider for this repository.",
Okay, this is handled by switching to organization.

2020-10-23 08:00 UTC, skoehnen commented on v3.0/products/fileRepository.schema.json
> +      "description": "Type of media stored in this repository.",
Fixed 👍

2020-10-23 08:00 UTC, skoehnen commented
All changes should be implemented.

2020-10-26 09:11 UTC, lzehl approved these changes

2020-10-26 09:12 UTC, lzehl commented
thanks @skoehnen

2020-10-26 09:12 UTC, merged