Create file bundle schema
openMetadataInitiative/openMINDS_core pull request #104
Opened 2020-10-22 16:12 UTC by skoehnen

Implementation of #80

2020-10-28 11:29 UTC, skoehnen commented on v3.0/products/fileBundle.schema.json
> +      "description": "???",
Description is missing

2020-10-28 11:45 UTC, lzehl commented on v3.0/products/fileBundle.schema.json
> +      "description": "???",
"Concept which was used to group the file instances into this file bundle"

2020-11-02 09:08 UTC, lzehl commented
@skoehnen if you add the "description" to the "groupedBy", I can merge this.

2020-11-02 09:09 UTC, lzehl requested changes

2020-11-02 09:09 UTC, lzehl commented on v3.0/products/fileBundle.schema.json
> +      "description": "???",
@skoehnen if you add the "description" to the "groupedBy", I can merge this.

2020-11-02 11:24 UTC, skoehnen commented on v3.0/products/fileBundle.schema.json
> +      "description": "???",
Done :+1:

2020-11-02 11:24 UTC, skoehnen commented
@lzehl Please check if the new location is correct.

2020-11-02 11:36 UTC, lzehl approved these changes

2020-11-02 11:36 UTC, merged