Create copyright.schema.json
openMetadataInitiative/openMINDS_core pull request #105
Opened 2020-10-23 07:56 UTC by jagru20

Related to #100 

As I did not find any definition of "year" in the schema

2020-10-23 08:16 UTC, skoehnen requested changes

2020-10-23 08:16 UTC, skoehnen commented on v3.0/products/copyright.schema.json
> +      "pattern":"([0-9][0-9][0-9][0-9])",
I would suggest this pattern 
`([0-9]{4})`
to simplify it a bit.

2020-10-23 08:16 UTC, skoehnen commented on v3.0/products/copyright.schema.json
> +  "title": "Copyright",
We haven't used the title in the other schemas.
Maybe it's a good idea to add it.

In any case we should be consistent, what do you think @lzehl ?

2020-10-23 08:30 UTC, jagru20 commented on v3.0/products/copyright.schema.json
> +  "title": "Copyright",
I have just used it, because it is also mentioned in [this](https://github.com/HumanBrainProject/openMINDS/wiki/Implementation) example, but if it is not necessary, we can omit it.

2020-10-23 08:38 UTC, skoehnen commented on v3.0/products/copyright.schema.json
> +  "title": "Copyright",
Okay, since it is in the implementation example we should definetly add it to the other schemas.

2020-10-23 08:39 UTC, skoehnen commented on v3.0/products/copyright.schema.json
> +  "title": "Copyright",
I will add an issue, so we don't forget it.

2020-10-23 08:51 UTC, jagru20 commented on v3.0/products/copyright.schema.json
> +      "pattern":"([0-9][0-9][0-9][0-9])",
of course :D

2020-10-23 11:53 UTC, UlrikeS91 requested changes
Just some suggestions for the descriptions, otherwise the schema looks good :)

2020-10-23 11:53 UTC, UlrikeS91 commented on v3.0/products/copyright.schema.json
> +      "description": "The person or organisation that holds the copyrights.",
I would suggest: "The person or organisation that holds the copyright." (no plural)

2020-10-23 11:53 UTC, UlrikeS91 commented on v3.0/products/copyright.schema.json
> +      "description": "Indicates the year in which the copyrights apply."
I would suggest "The year in which the copyright was issued." @skoehnen, is that correct? Are copyrights issued?

2020-10-26 07:25 UTC, skoehnen commented on v3.0/products/copyright.schema.json
> +      "description": "Indicates the year in which the copyrights apply."
I think granted is better in this context, because issued implies that some other entity vetted the copyright of the data.

You can of course register your intellectual property in some countries, but that is more of a legal tool to help you during litigation. That way you can establish a point in time where you established your copyright.
I don't think that this is necessary for our use-cases.

2020-10-26 08:01 UTC, lzehl commented on v3.0/products/copyright.schema.json
> +      "description": "The person or organisation that holds the copyrights.",
I agree

2020-10-26 08:01 UTC, lzehl commented on v3.0/products/copyright.schema.json
> +      "description": "Indicates the year in which the copyrights apply."
@apdavison what do you think?

2020-10-26 08:21 UTC, jagru20 commented on v3.0/products/copyright.schema.json
> +      "description": "Indicates the year in which the copyrights apply."
I am no expert in this, but does not "granted" also implies the verification by someone else? To me "The year for which copyright is claimed" sounds appropriate.

2020-10-26 08:36 UTC, lzehl commented on v3.0/products/copyright.schema.json
> +      "description": "Indicates the year in which the copyrights apply."
From the definition point of view I think the copyright year usually corresponds to the year the work was published. 
Definition from schema.org: "The year during which the claimed copyright for the CreativeWork was first asserted." I suggest to stay close to this one.

2020-10-26 08:41 UTC, UlrikeS91 commented on v3.0/products/copyright.schema.json
> +      "description": "Indicates the year in which the copyrights apply."
I found something similar: "The first year of publication of the copyright.". 

What about: **"The year during which the copyright was first asserted."**?

2020-10-26 08:48 UTC, jagru20 commented on v3.0/products/copyright.schema.json
> +      "description": "Indicates the year in which the copyrights apply."
Sounds good.

2020-10-26 08:50 UTC, lzehl commented on v3.0/products/copyright.schema.json
> +      "description": "Indicates the year in which the copyrights apply."
:+1:

2020-10-26 08:55 UTC, jagru20 commented on v3.0/products/copyright.schema.json
> +      "pattern":"([0-9]{4}])",
One thing just came to my mind: How would we deal with cases where copyright is intended to be a span of years? We could make the year property an array containing each individual year within the range, or we could use the `oneOf` operator to have the choice between a pattern for a single year and a range of years.

2020-10-26 08:57 UTC, jagru20 commented on v3.0/products/copyright.schema.json
> +      "pattern":"([0-9]{4}])",
Or do we simply always choose the first year (as we just decided to write in the description)?

2020-10-26 09:04 UTC, lzehl commented on v3.0/products/copyright.schema.json
> +      "pattern":"([0-9]{4}])",
first year as in the discription. The copyright span is counted from that year on.

2020-10-26 09:21 UTC, lzehl approved these changes

2020-10-26 09:21 UTC, UlrikeS91 approved these changes

2020-10-26 09:22 UTC, lzehl commented
@UlrikeS91 or @skoehnen feel free to merge this one

2020-10-26 09:34 UTC, merged