Create softwareFeature.schema.json
openMetadataInitiative/openMINDS_core pull request #128
Opened 2020-10-26 14:31 UTC by jagru20

2020-10-26 14:43 UTC, lzehl commented
@jagru20 I changed it to a draft or is it ready for the review?

2020-10-27 11:46 UTC, lzehl commented
@jagru20 are you done with this? should I start the review?

2020-10-27 11:47 UTC, jagru20 commented
Yes, I think it is ready to be reviewed...

2020-10-27 12:00 UTC, lzehl requested changes
"request change" is misleading but I would like to clarify my questions/suggestions first

2020-10-27 12:00 UTC, lzehl commented on v3.0/products/softwareFeature.schema.json
> +  "title": "Software Feature",
I would always use the label used for schema also for the title: meaning "softwareFeature"
Or we choose a display label which I would not capitalize: "software feature"

2020-10-27 12:00 UTC, lzehl commented on v3.0/products/softwareFeature.schema.json
> +    "definition":{
What is the definition? Is this a link to an ontology term? Could you explain a bit more?

2020-10-27 12:50 UTC, jagru20 commented on v3.0/products/softwareFeature.schema.json
> +  "title": "Software Feature",
Ok I was also wondering if this was correct. I thought it was rather meant to be a display label, because it is what shows up in the KG editor later on? However, of course we can make it not capitalized.

2020-10-27 13:51 UTC, jagru20 commented on v3.0/products/softwareFeature.schema.json
> +    "definition":{
`definition` is a link to an external resource, defining the specific feature. For example the value of `definition` for the feature "command line interface" would be https://www.wikidata.org/wiki/Q189053

2020-10-27 16:47 UTC, lzehl commented on v3.0/products/softwareFeature.schema.json
> +    "definition":{
Mh... this one should then maybe be renamed. Let's do that though in another PR.

2020-10-27 16:48 UTC, lzehl commented on v3.0/products/softwareFeature.schema.json
> +  "title": "Software Feature",
I chatted with @olinux in the meantime. Go for a display label, but I suggest do not capitalize it "software feature"

2020-10-28 08:05 UTC, jagru20 commented on v3.0/products/softwareFeature.schema.json
> +    "definition":{
You mean the renaming, but I change the `description` of definition in this one, right?

2020-11-02 09:14 UTC, merged