Changing / Extending ParameterSetting
openMetadataInitiative/openMINDS_core pull request #177
Opened 2021-03-03 14:53 UTC by lzehl

The changes in this PR were discussed in issue #161

2021-03-03 15:04 UTC, lzehl commented
@apdavison let me know if you are too busy to review this, I can also ask Ulrike or Oli. Hope the changes will improve the logic a bit for the settings.

2021-03-04 07:55 UTC, UlrikeS91 requested changes
See comments. There is one error that needs to be fixed (in `parameterSetting`) for sure.

@apdavison, your feedback to my question about the multiple values for `numericalParameter` would be very useful. Your general review as requested by @lzehl would be even better, of course :)

2021-03-04 07:55 UTC, UlrikeS91 commented on schemas/research/numericalParameter.schema.tpl.json
> +    }
Why would you expect 1 - N `"value"` here? Can you give an example for when this would be useful? 

Personally, I can't come up with a good example. I think that name + value should be 1:1 (and you can still give a `quantitativeValueRange` if a single value is not enough). Additionally, `parameterSetting` allows the use of several numerical parameters. So, if you need several `"values"` for a `numericalParameter` related to the same `"name"`, one can just create several `numericalParameters` with the same `"name"` but different `"values"`, right?

2021-03-04 07:55 UTC, UlrikeS91 commented on schemas/research/parameterSetting.schema.tpl.json
> +    "setting"
Shouldn't this be `"parameter"`? The property `"setting"` at least doesn't exist. So, either `"parameter"` in line 20 needs to be changed to `"setting"` or vice versa.

2021-03-04 07:55 UTC, UlrikeS91 commented on schemas/research/parameterSetting.schema.tpl.json
> +    "parameters": {
If you want to stick to `"parameters"` (see comment above), you should change the property name to its singular to stick to our logic that properties where one linkedType/embeddedType is a valid option, should be singular. 

--> change to `"parameter"` (or `"setting"`)

2021-03-04 09:59 UTC, lzehl commented on schemas/research/numericalParameter.schema.tpl.json
> +    }
One use case I imagined (quantitative values are simplified): 
"name": "stimulusTriggerPoints", 
"value": [1s, 2s, 4s]

In such a case, I would find entering all of them with separate names a bit cumbersome.

2021-03-04 10:01 UTC, lzehl commented on schemas/research/parameterSetting.schema.tpl.json
> +    "setting"
:see_no_evil: that's a stupid one from my side. needs to be "parameters". I'll change it.

2021-03-04 10:04 UTC, lzehl commented on schemas/research/parameterSetting.schema.tpl.json
> +    "parameters": {
We need to rethink this rule. We anyway do not stick to it fully (there are much more cases where this is not followed starting with our syntax "_linkedTypes", etc...) But I'll change it for now.

2021-03-04 10:37 UTC, apdavison reviewed
I think my original idea is that `NumericalParameter` and `StringParameter` would replace `ParameterSetting`, whereas here it seems that `ParameterSetting` has become a container. I think that's fine, although in that case the name `ParameterSet` would be better, I think.

2021-03-04 10:37 UTC, apdavison commented on schemas/research/numericalParameter.schema.tpl.json
> +    }
What about adding ArrayParameter, to explicitly allow arrays of numerical values, and make NumericalParameter single valued?

2021-03-04 10:37 UTC, apdavison commented on schemas/research/stringParameter.schema.tpl.json
> +      "_instruction": "Enter a semantic value for this string parameter."
I don't understand why "semantic" is used here

2021-03-04 10:49 UTC, lzehl commented
> I think my original idea is that `NumericalParameter` and `StringParameter` would replace `ParameterSetting`, whereas here it seems that `ParameterSetting` has become a container. I think that's fine, although in that case the name `ParameterSet` would be better, I think.

@apdavison yes that is something we discussed in the issue in order to facilitate the registration of highly related parameters without having to make this relation clear in the name of the parameter (e.g., used agent, used concentration of that agent).

I'm happy to change the Schema name into "ParameterSet" and the corresponding property as well in ProtocolExecution.

2021-03-10 08:52 UTC, lzehl commented on schemas/research/stringParameter.schema.tpl.json
> +      "_instruction": "Enter a semantic value for this string parameter."
@apdavison I was searching for alternative word for "string". Any suggestions? "text value" ?

For the comment above: I don't see the advantage to introduce a PropertArray, also because it is only useful for numerical values, would it not? and would just allow multiple quantitativeValues instead of one. We never differentiated between this in other schemas, if both single or array entries are allowed. What do you think?

2021-03-10 09:11 UTC, apdavison commented on schemas/research/stringParameter.schema.tpl.json
> +      "_instruction": "Enter a semantic value for this string parameter."
Sure, "Enter a text value for this parameter" or just "Enter a value for this parameter".

I agree about ArrayParameter. What could however be useful is QuantitativeValueArray, which would make it easier to enter arrays if the units could be specified only once (e.g. if you have an array of size 100, having to specify the units separately for each element in the array makes it very verbose).

2021-03-10 09:21 UTC, lzehl commented on schemas/research/stringParameter.schema.tpl.json
> +      "_instruction": "Enter a semantic value for this string parameter."
@apdavison :smile: I just thought about the same thing for the quantitativeValues. I agree that this would be useful, the only problem I see is how to handle uncertainties in a QuantitativeValueArray. Any suggestions?

2021-03-10 09:26 UTC, apdavison commented on schemas/research/stringParameter.schema.tpl.json
> +      "_instruction": "Enter a semantic value for this string parameter."
For the uncertainty, it should be possible to specify either a single pair of values (same uncertainty for all values in the array), or a 2 x N array of uncertainty values.

2021-03-10 09:42 UTC, lzehl commented on schemas/research/stringParameter.schema.tpl.json
> +      "_instruction": "Enter a semantic value for this string parameter."
@apdavison If you agree, let's get back to the QuantitativeValueArray in the next revision. You think the remaining issues are solved in this PR?

2021-03-10 09:45 UTC, lzehl commented on schemas/research/stringParameter.schema.tpl.json
> +      "_instruction": "Enter a semantic value for this string parameter."
@apdavison feel free to merge it then when you are happy

2021-03-10 09:49 UTC, apdavison commented
@UlrikeS91 were all your requested changes taken into account?

2021-03-10 10:14 UTC, UlrikeS91 requested changes
@lzehl, I noticed some more things now. See comments.

2021-03-10 10:14 UTC, UlrikeS91 commented on schemas/research/numericalParameter.schema.tpl.json
> +    }
I think it's fine to have the array here. @lzehl example is valid, and it won't hurt to have it as an array. 

But: `"_linkedTypes":` is wrong, isn't it? We don't want to recycle quantitativeValue(Range). This should be `"_embeddedTypes":`, or?
If `"_linkedTypes":` is correct, `uniqueItems` should be removed. Then you may as well recycle the exact same value ;) But I'm pretty sure that we don't want them since we never allowed this before (see e.g. `specimenState` schema).

2021-03-10 10:14 UTC, UlrikeS91 commented on schemas/research/protocolExecution.schema.tpl.json
>        "_instruction": "Add all important parameter settings defining this protocol execution.",
Change to: "Add all important parameter sets defining this protocol execution."

(Does "sets" sound a bit strange, or is it just me?)

2021-03-10 10:17 UTC, UlrikeS91 commented
> @UlrikeS91 were all your requested changes taken into account?

@apdavison, yes, there was a lot of other things being discussed in parallel but I think everything was covered.

2021-03-10 16:38 UTC, lzehl commented on schemas/research/protocolExecution.schema.tpl.json
>        "_instruction": "Add all important parameter settings defining this protocol execution.",
@UlrikeS91 you are right in all comments. Thanks for being so thorough! I've updated the corresponding descriptions (mentioning setting) and the _embeddedTypes (incl. deletion of uniqueItems)

2021-03-11 10:27 UTC, UlrikeS91 approved these changes

2021-03-11 10:27 UTC, merged