Peyman changing semantically anchored to anatomical location
openMetadataInitiative/openMINDS_core pull request #209
Opened 2021-06-15 14:16 UTC by Peyman-N

As the discussion between me, Andrew and Lyuba. I am moving the anatomical location from `protocolExecution` to the `tissueSample`. This was necessary as a given `protocolExecution` can act on multiple brain regions, therefore the relationship between `tissueSample` and its location becomes ambiguous. 
To solve this ambiguity as we discuss it, I have removed the `semanticallyAnchoredTo` property from `protocolExecution` and, added a new property named `anatomicalLocation` to the `tissueSample`.
This change would make both `protocolExecution` and `tissueSample` more intuitive. As currently it exist two methods for describing the target of a `protocolExecution`, one through `studyTarget` property and other one through `semanticallyAnchoredTo` property. While we there is no tool for giving any information about location of a `tissueSample`.

2021-06-15 14:22 UTC, Peyman-N commented
On a second note I wanted to make the `anatomicalLocation`'s type only `controlledTerms/UBERONParcellation` but this was not a decision that I could have made alone.

2021-06-15 14:25 UTC, lzehl reviewed
@olinux seems good to me (except for the missing type), only question: should this PR be merged with yours (PR #204)?

2021-06-15 14:26 UTC, lzehl requested changes

2021-06-15 14:26 UTC, lzehl commented on schemas/research/tissueSample.schema.tpl.json
> +        "https://openminds.ebrains.eu/sands/AnatomicalEntity"
Should also link to https://openminds.ebrains.eu/sands/ParcellationEntity

2021-06-15 14:29 UTC, lzehl commented
> On a second note I wanted to make the `anatomicalLocation`'s type only `controlledTerms/UBERONParcellation` but this was not a decision that I could have made alone.

This should not be the case. UBERON is super generic and if you can be more precise you should be (either by providing a link to an atlas parcellation (parcellation entity) or to your own parcellation name (anatomical entity)).

2021-06-15 14:30 UTC, lzehl commented on schemas/research/tissueSample.schema.tpl.json
> +        "https://openminds.ebrains.eu/sands/AnatomicalEntity"
And it should be https://openminds.ebrains.eu/sands/CustomAnatomicalEntity

2021-06-15 17:37 UTC, Peyman-N commented on schemas/research/tissueSample.schema.tpl.json
> +        "https://openminds.ebrains.eu/sands/AnatomicalEntity"
Done!

2021-06-15 18:24 UTC, lzehl approved these changes

2021-06-15 18:25 UTC, lzehl commented
@olinux if this does not collide with your PR #204 and you double checked the changes feel free to merge.

2021-06-18 14:13 UTC, lzehl commented
@Peyman-N I've just merged a PR from Oli (#204) which will require some conflict solving in your PR. It should be not too much trouble though. Could you have a look and resolve the conflicts?

2021-06-18 14:24 UTC, lzehl commented
@Peyman-N I've solved it already :smile: I've realized that there was an error in the master so I've corrected it directly while solving the conflict.

2021-06-18 14:28 UTC, lzehl commented
@olinux Activity Schema is now part of openMINDS_core,  the property "semanticallyAnchoredTo" is removed from the ProtocolExecution Schema, and the TissueSample Schema has a "anatomicalLocation" property now.

2021-06-18 14:28 UTC, merged

2021-06-18 15:40 UTC, Peyman-N commented
@lzehl sorry, I just saw your comment. :sweat_smile:  Anyhow thanks a lot :smile: