Reassessment of BehavioralTask
openMetadataInitiative/openMINDS_core pull request #212
Opened 2021-06-23 08:12 UTC by lzehl

Cf. #210 

1) Intro of BehavioralTask schema
For now only contains properties "fullName", "shortName", & "description".
Future: will be extended by properties linking to controlled terms that will characterize the behavioral task (in a more standardized way).

2) Remove "behavioralTask" property from Protocol schema.

3) Link BehavioralTask schema to ProtocolExecution schema.

2021-06-23 10:00 UTC, UlrikeS91 requested changes
General first: The draft looks correct. Technically, it could be merged. But controlledTerms/BehavioralTask (+ instances) should be removed. This is (obviously) not included in this PR, but should be done in parallel. 

I didn't give any comment in the related issue, but the result of that discussion makes sense to me and how you intend to solve it here. 
There is only one thing that I'm wondering about: This solution puts BehavioralTasks and Protocols more or less on the same level. But in this PR, you added them with their own properties to DatasetVersion (DSV) and ProtocolExecution (PrEx). Wouldn't it make more sense to collect them under the same property? 
Specifically, I'm struggling with Protocol being a required property while BehavioralTask isn't. Does that mean that a BehavioralTask cannot replace a Protocol? Does it always need to be at least one Protocol and optionally BehavioralTask(s) in addition? I think I would have viewed a BehavioralTask as something similar to a Protocol and potentially something that can stand on its own (without a protocol). And yes, this is indirectly the answer I never gave to your last question in the issue #210 ;) 
Since both properties allow N Protocols/BehavioralTasks, it would not be a problem to merge it under one property name, unless you actively intended to require at least one protocol of course.

2021-06-23 10:16 UTC, lzehl commented
@UlrikeS91 thanks for your feedback. I actually thought about merging them into one property as you discuss above, but there is indeed a difference: a behavioral task although in principle could be done on its own, within an experiment it cannot be performed without having a technical protocol in place to record / image the behavior. The other way around: a technical protocol has to be used for any experiment, but does not necessarily require a behavioral task present as well. This is why we kept behavioral task separate from techniques in the past, and why it is not good to merge them (since we cannot state: should have at least one protocol, can have additionally more protocols or behavioral tasks). Does this answer your concern?

2021-06-23 10:43 UTC, UlrikeS91 commented
> @UlrikeS91 thanks for your feedback. I actually thought about merging them into one property as you discuss above, but there is indeed a difference: a behavioral task although in principle could be done on its own, within an experiment it cannot be performed without having a technical protocol in place to record / image the behavior. The other way around: a technical protocol has to be used for any experiment, but does not necessarily require a behavioral task present as well. This is why we kept behavioral task separate from techniques in the past, and why it is not good to merge them (since we cannot state: should have at least one protocol, can have additionally more protocols or behavioral tasks). Does this answer your concern?

Yes, this makes sense :) Then it also makes sense to keep them separate and to keep BehavioralTask optional (0 - N), while Protocol is required (1 - N). 

I think this can change from draft to reality now ;)

2021-06-23 10:44 UTC, UlrikeS91 approved these changes

2021-06-23 10:49 UTC, lzehl commented
@Peyman-N & @apdavison this PR might affect you as well.

2021-06-24 06:58 UTC, UlrikeS91 commented
I just noticed that ParameterSet needs some adjustments because of this, too, @lzehl.

2021-06-24 07:06 UTC, lzehl commented
@UlrikeS91 why?

2021-06-24 10:19 UTC, UlrikeS91 commented
Because it has behavioralTask as well: 
````
    "relevantFor": {
      "_instruction": "Add the technique or behavioral task where this set of parameters is used in.",
      "_linkedTypes": [
        "https://openminds.ebrains.eu/controlledTerms/BehavioralTask",
        "https://openminds.ebrains.eu/controlledTerms/Technique"
      ]
    }
````
Shouldn't that at least point to the new schema for BehavioralTask then?

2021-06-24 10:41 UTC, lzehl commented
@UlrikeS91 mh... not sure... let's do it though.

2021-06-24 10:43 UTC, lzehl commented
@UlrikeS91 done

2021-06-28 15:46 UTC, lzehl commented
@UlrikeS91 @Peyman-N & @apdavison FYI

Based on requests from Jan to simplify the minimal openMINDS metadata model even more and based on issues that came up during (partially respective) technical discussions with Oli the following changes will be made in this PR as well.

1) Dataset Version will not link to Protocols but to Techniques. [minimal track request from Jan]
2) Protocol Executions will link additionally to Dataset Version (required; count 1) to emphasize the fact that a PE cannot be reused across Dataset Versions. [idea from @olinux; will require later on a graph validation]

@apdavison if the later point is also true for all your Activity extending schemas we could later move this linkage also to Activity.

2021-06-28 15:50 UTC, olinux approved these changes

2021-06-28 15:56 UTC, lzehl commented
@olinux done. you can verify and merge if everything is in place.

2021-07-02 11:59 UTC, merged