Adding mediatypes
openMetadataInitiative/openMINDS_core pull request #216
Opened 2021-07-30 08:59 UTC by jagru20

2021-07-30 09:51 UTC, apdavison requested changes
There is some redundancy here with respect to existing entries. One I spotted is that igor.jsonld is essentially identical to the existing igorpro.jsonld.

Can I suggest using the file extensions to identify other possible duplicates?

2021-07-30 09:54 UTC, apdavison commented
Possibly a bigger issue: shouldn't this PR be made against https://github.com/HumanBrainProject/openMINDS_instances ?

Or has the process been changed? @lzehl can you comment?

2021-08-02 07:41 UTC, lzehl commented
@apdavison there was an update on where to store the instances (announced via slack). Sorry if that got lost. I think I should do such announcements via email... We moved the instances to the corresponding metadata model repos (again) because they are version dependent, and we decided it is easier to handle them then directly within the corresponding version branch. If they are backwards compatible we should have them on all version branches of course (this might not yet be the case, I'm still organizing the cleanup). Another question though: how should we handle the openMINDS_instances GitHub? Should we delete it after making an announcement on the README or should we keep it?

2021-08-02 07:55 UTC, lzehl commented
@jagru20 & @apdavison for the potential duplicates: the extensions might not help very much to identify duplicates. On the one hand I expect that two versions of the "same format" will get separate entries, but would most likely have the same extension(s). On the other hand all the ambiguous extensions (e.g., csv, tsv, json, etc) which have one generic media type, but can have multiple content types for specific applications will pop up as well.

2021-08-02 07:57 UTC, lzehl commented
@jagru20 & @apdavison another question: what about the generic media types (csv, tsv, json, etc)? Should the "relatedMediaType" link to those also for the application specific content type? Or should we allow multiple content types for files, file bundles, and file repositories, so that they can link to the generic & the specific content type?

2021-08-02 08:04 UTC, lzehl requested changes
I agree with @apdavison that the potential duplicates should be identified and eliminated. 

I would suggest to add the matching "relatedMediaType" to the entries which definitely have one (e.g. image/vnd.adobe.photoshop -> https://www.iana.org/assignments/media-types/image/vnd.adobe.photoshop)

2021-08-02 08:18 UTC, apdavison commented
Where we have application-specific content types that are based on a more generic type, the generic type is generally indicated with a "+".

For example, for IPython/Jupyter notebooks the content type is "application/x-ipynb+json", so indicating that any application that can read JSON can open this file, although of course the full functionality is only available if the application can interpret the JSON as a Jupyter notebook.

2021-08-02 08:32 UTC, lzehl commented
@apdavison I know, but should we still use a direct connection (either via "relatedMediaType" or via multiple contentTypes) to indicate that all CSVs (independent of their specification) can be viewed with the tools registered for the generic CSV media type?

2021-08-02 08:48 UTC, apdavison commented
@lzehl I think all three approaches would work, i.e.:
1. direct connection via "relatedMediaType"
2. direct connection via multiple "contentType"s
3. parse the content type name to use the "+"part

I don't have a strong preference, I have a weak preference for option 3.

2021-08-02 08:54 UTC, lzehl commented
@apdavison I agree. We can adopt later. But as a comment: I think 3 should be always used (based on the naming convention), and in addition we can introduce 1 or 2 (or 4: intro of property "parentMediaType").

2021-08-17 08:52 UTC, lzehl commented
@jagru20 do you need help for this PR ?

2021-08-17 09:12 UTC, jagru20 commented
@lzehl sorry for the delay in this pr. Of course do the redundancies need to be eliminated. I think a little help would be quite useful here. I hope I understand the above discussion correctly when assuming that we add any relatey mediatypes at a later point in time?

2021-08-17 09:18 UTC, jagru20 commented on instances/data/contentTypes/igor.jsonld
> +{
can be deleted

2021-08-17 09:21 UTC, jagru20 commented on instances/data/contentTypes/moleculardevices.axon.jsonld
> +{
this is redundant to [abf.jsonld](https://github.com/HumanBrainProject/openMINDS_core/blob/v3/instances/data/contentTypes/abf.jsonld) But I would prefer the file naming of this version, as it is more precise, what do you think @apdavison @lzehl ?

2021-08-17 09:22 UTC, jagru20 commented on instances/data/contentTypes/moleculardevices.axon.jsonld
> +		"Axon™ Binary File format"
is the use of the (TM) character a problem?

2021-08-17 09:34 UTC, lzehl commented on instances/data/contentTypes/moleculardevices.axon.jsonld
> +		"Axon™ Binary File format"
@olinux should we support markdown for all text fields? this formatting is not only an issue/question for this item but all text fields within openMINDS.

2021-08-17 09:34 UTC, lzehl commented on instances/data/contentTypes/moleculardevices.axon.jsonld
> +{
I leave this to @apdavison

2021-08-17 09:36 UTC, lzehl commented
> @lzehl sorry for the delay in this pr. Of course do the redundancies need to be eliminated. I think a little help would be quite useful here. I hope I understand the above discussion correctly when assuming that we add any related media types at a later point in time?

@jagru20 yes the media types can be added later.

2021-08-17 09:39 UTC, jagru20 commented on instances/data/contentTypes/neo.ascii.image.jsonld
> +{
this one is redundant to [asciimage.jsonld](https://github.com/HumanBrainProject/openMINDS_core/blob/v3/instances/data/contentTypes/asciiimage.jsonld)

2021-08-17 09:42 UTC, jagru20 commented on instances/data/contentTypes/neo.ascii.signal.jsonld
> +{
redundant https://github.com/HumanBrainProject/openMINDS_core/blob/v3/instances/data/contentTypes/asciisignal.jsonld

2021-08-17 09:42 UTC, jagru20 commented on instances/data/contentTypes/neo.ascii.spiketrain.jsonld
> +{
redundant https://github.com/HumanBrainProject/openMINDS_core/blob/v3/instances/data/contentTypes/asciispiketrain.jsonld

2021-08-17 09:44 UTC, lzehl commented
@jagru20 for the redundant entries: should we identify them within the review of this PR? this might be a bit cumbersome... in any case I maybe able to help you towards the end of this week.

2021-08-19 08:40 UTC, jagru20 commented
I have prepared a commit, where I tried to eliminate the redundancies and keep as much as information as possible available.  Although I would prefer to hear @apdavison thoughts on the filename thing first, I can also just push it and we discuss that later as the essential information in the file contents is the same or extended.

2021-08-23 08:55 UTC, apdavison commented on instances/data/contentTypes/neo.ascii.image.jsonld
> +{
@jagru20 I'm happy for you to modify the filenames

2021-08-23 08:58 UTC, apdavison commented on instances/data/contentTypes/moleculardevices.axon.jsonld
> +		"Axon™ Binary File format"
This is not a Markdown question, I don't think. I think the text fields should be unicode, UTF-8 encoding. ™ is therefore a valid character.

2021-08-23 08:59 UTC, lzehl commented on instances/data/contentTypes/moleculardevices.axon.jsonld
> +		"Axon™ Binary File format"
yes, Andrew is right. it should be fine

2021-08-24 17:19 UTC, lzehl requested changes
Hi @jagru20 thanks a lot for this huge PR. Are all deleted files replaces by a more accurate one from you? I think I did not find a matching new one for all of the deleted once. 

@apdavison some of my comments might be also solvable by you.

2021-08-24 17:19 UTC, lzehl commented on instances/data/contentTypes/blackrockmicrosystems.cerebus.jsonld
> +		".nsx"
I think this needs to be changed to the specific extensions (.ns1, .ns2, .ns3, .ns4, .ns5, .ns6)

There is also a neural event data format from blackrock (.nev). If not captured yet this should be added as a content type as well

2021-08-24 17:19 UTC, lzehl commented on instances/data/contentTypes/cml.jsonld
> +	"@id": "https://openminds.ebrains.eu/instances/contentTypes/chemical/x-cml",
what does "chemical" mean in this context??

2021-08-24 17:19 UTC, lzehl commented on instances/data/contentTypes/fmri.jsonld
> +	"@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.fmri",
I don't get this one... if this is .nii OR .nii.gz means this is NIftI (format 1 or 2?) in dimensions (2D, 3D, 4D) the latter dimension file contains time data as well (but I do not know that this has the extension .dtseries.nii).
What is software connected to this?

2021-08-24 17:19 UTC, lzehl commented on instances/data/contentTypes/ge-healthcare-life-sciences.amersham-biosciences-gel.jsonld
> +	"synonym": null
is there really no better synonym for this quite long and complicated name?

2021-08-24 17:19 UTC, lzehl commented on instances/data/contentTypes/hyland.brainwaredam.jsonld
> +	"@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.hyland.brainwaredam",
I guess brainwaredam.jsonld is a duplicate and needs to be deleted then??

2021-08-24 17:19 UTC, lzehl commented on instances/data/contentTypes/hyland.brainwaref32.jsonld
> +	"@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.hyland.brainwaref32",
brainwaref32.jsonld is then a duplicate and needs to be deleted?

2021-08-24 17:19 UTC, lzehl commented on instances/data/contentTypes/hyland.brainwaresrc.jsonld
> +	"@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.hyland.brainwaresrc",
brainwaresrc.jsonld is a duplicate then and needs to be deleted?

2021-08-24 17:19 UTC, lzehl commented on instances/data/contentTypes/lavision.imspector.jsonld
> +	"@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.lavision.imspector",
is this the same as imspector.jsonld ??

2021-08-24 17:19 UTC, lzehl commented on instances/data/contentTypes/matlab.jsonld
> +	"@id": "https://openminds.ebrains.eu/instances/contentTypes/text/x-matlab",
filename should be x-matlab as well. Question: what about matlab files with .mat ? is this a different content type?

2021-08-24 17:19 UTC, lzehl commented on instances/data/contentTypes/minc.jsonld
> +	"@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.minc",
there are different minc versions as far as I know. do we cover them?

2021-08-24 17:19 UTC, lzehl commented on instances/data/contentTypes/nest.jsonld
> +	"@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.nest",
what software is this?

2021-08-24 17:19 UTC, lzehl commented on instances/data/contentTypes/nifti.1.jsonld
> +	"@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.nifti.1",
could you update nifti.2 accordingly?

2021-08-24 17:19 UTC, lzehl commented on instances/data/contentTypes/ome.tiff.jsonld
> +		"ome.tf2",
dot missing

2021-08-24 17:19 UTC, lzehl commented on instances/data/contentTypes/ome.tiff.jsonld
> +		"ome.tiff"
dot missing

2021-08-24 17:19 UTC, lzehl commented on instances/data/contentTypes/python.jsonld
> +	"@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.python",
do we need to cover the different versions?

2021-08-24 17:19 UTC, lzehl commented on instances/data/contentTypes/raw.binarysignal.jsonld
> +	"@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.raw.binarysignal",
is this different to raw.jsonld?

2021-08-24 17:19 UTC, lzehl commented on instances/data/contentTypes/raw.mcs.jsonld
> +	"@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.raw.mcs",
rawmcs.jsonld is a duplicate then and should be deleted?

2021-08-24 17:19 UTC, lzehl commented on instances/data/contentTypes/traces .jsonld
> +	"@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.traces ",
delete space

2021-08-24 17:19 UTC, lzehl commented on instances/data/contentTypes/traces .jsonld
> +	"name": "application/vnd.traces ",
delete space

2021-09-16 16:24 UTC, lzehl commented
@jagru20 one more thing I noticed: the blackrock formats need to be splitted I think into .ns2 - .ns6 and .nev...

2021-09-17 08:35 UTC, jagru20 commented
> 
> 
> @jagru20 one more thing I noticed: the blackrock formats need to be splitted I think into .ns2 - .ns6 and .nev...

you mean splitting them into separate contenttypes instead of listing the separate extensions in the application/vnd.blackrockmicrosystems.cerebus?

2021-09-19 11:48 UTC, lzehl commented
> > @jagru20 one more thing I noticed: the blackrock formats need to be splitted I think into .ns2 - .ns6 and .nev...
> 
> you mean splitting them into separate contenttypes instead of listing the separate extensions in the application/vnd.blackrockmicrosystems.cerebus?

@jagru20 yes. At least nev vs nsX need to be different content types because they need different loading routines. For the nsX we can discuss. @apdavison what is your though about this ?

2021-09-19 13:04 UTC, apdavison commented
My understanding is that a given recording session is typically split over a nev and one or more nsX files with the same file name prefix, so you need all files to correctly load the data. This is how Neo handles them in any case: see https://github.com/NeuralEnsemble/python-neo/blob/master/neo/rawio/blackrockrawio.py

Probably we should have a separate content type for each, plus maybe a content type applied to a FileBundle that would represent the group of files belonging to the same recording.

2021-09-19 15:02 UTC, lzehl commented
@apdavison sounds good. One contentType for each and one for "blackrock parallel recordings".

2021-09-21 13:29 UTC, jagru20 commented
Sorry for double asking but "for each" in this case means one for all .nsx files, listing their possible extensions and one for .nev, right? Sorry for double asking. Otherwise, this would not make sense because, the loading routine for different .nsx files would only differ depending on their header contents right?

2021-09-21 13:57 UTC, jagru20 commented on instances/data/contentTypes/cml.jsonld
> +	"@id": "https://openminds.ebrains.eu/instances/contentTypes/chemical/x-cml",
this is the type naming as proposed by the chemical MIME project (cf. https://www.ch.ic.ac.uk/chemime/ or https://en.wikipedia.org/wiki/Chemical_Markup_Language) but as this is unofficial and "only" de facto standard since 1998 and apparently xml based, I think we could change this to  `text/x-cml+xml`

2021-09-21 14:15 UTC, jagru20 commented on instances/data/contentTypes/fmri.jsonld
> +	"@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.fmri",
I think the id/name should be reworked here. The fileformat is CIFTI which makes use of NIFTI-2 (see https://wiki.humanconnectome.org/display/PublicData/HCP+Users+FAQ) there it also states that these files must not be gzipped if you want to access it, but can be zipped for transferring them. I think this is why this gets confusing. I suggest splitting this up or deleting the .nii.gz extension, as this does not seem to add value here, it needs to be unzipped anyway most likely

2021-09-21 18:16 UTC, lzehl commented
> Sorry for double asking but "for each" in this case means one for all .nsx files, listing their possible extensions and one for .nev, right? Otherwise, this would not make sense because, the loading routine for different .nsx files would only differ depending on their header contents right?

@apdavison please correct me if I'm wrong: we would need contentTypes for each nsX and one for nev. If I remember correctly the nsX differ in their structure, because they are supported by different versions? @jagru20 sorry for the confusion, but it's too long ago that I worked with those files... In addition, Andrew suggested to have a blackrock contentType for parallel recordings (for a file bundle) that can indicate when several nsX and a nev are actually recorded in parallel and should be looked at together.

2021-09-21 18:18 UTC, lzehl commented on instances/data/contentTypes/cml.jsonld
> +	"@id": "https://openminds.ebrains.eu/instances/contentTypes/chemical/x-cml",
your suggestion sounds nicer (more consistent with the others) to me. @apdavison what do you think?

2021-09-21 18:22 UTC, lzehl commented on instances/data/contentTypes/fmri.jsonld
> +	"@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.fmri",
Why not make use of the name "CIFTI-2" then? in combination with NIFTI-2 if that is the base? @apdavison your opinion/suggestion? (I don't want to suggest a name since the two of you are much more familiar with the convention)

2021-09-22 09:00 UTC, jagru20 commented on instances/data/contentTypes/fmri.jsonld
> +	"@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.fmri",
yes, that's what I meant. I suggest `application/fmri.cifti-2̀  note that I did not add a `+nifti` suffix because I am not sure if (and don't think) it is possible to open a cifti-2 file with any generic nifti-2 viewer. 

However, I would add the link to the specification file also: https://www.nitrc.org/forum/attachment.php?attachid=341&group_id=454&forum_id=1955

2021-09-22 09:13 UTC, lzehl commented on instances/data/contentTypes/fmri.jsonld
> +	"@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.fmri",
looks good :+1:

2021-10-12 09:29 UTC, jagru20 commented on instances/data/contentTypes/ge-healthcare-life-sciences.amersham-biosciences-gel.jsonld
> +	"synonym": null
I'm adding "GEL" as a synonym.

2021-10-12 10:03 UTC, jagru20 commented on instances/data/contentTypes/lavision.imspector.jsonld
> +	"@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.lavision.imspector",
I am not completely sure about this, but I think they are different, because they are from different companies (abberior vs. lavision biotec) and bound to software distributed with their hardware. I would add abberior to the name of the other imspector to make the differnce clear.

2021-10-12 11:52 UTC, jagru20 commented on instances/data/contentTypes/matlab.jsonld
> +	"@id": "https://openminds.ebrains.eu/instances/contentTypes/text/x-matlab",
The "x-" prefix is usually (at IANA) used to mark that a contenttype is experimental, thus not fully specified. I rather suggest deleting the prefix. This also applies to several other contenttypes.

2021-10-12 12:10 UTC, jagru20 commented on instances/data/contentTypes/minc.jsonld
> +	"@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.minc",
Not yet, because apparently there was no need to distinguish between them until now, I think.

2021-10-12 12:11 UTC, jagru20 commented on instances/data/contentTypes/nest.jsonld
> +	"@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.nest",
nest is a simulator for spiking neural networks, see https://nest-simulator.org/

2021-10-12 12:32 UTC, jagru20 commented on instances/data/contentTypes/python.jsonld
> +	"@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.python",
I don't think so. If I am correct, the file specification of a python script file should not be affected by the version it makes use of, right?

2021-10-12 12:35 UTC, jagru20 commented on instances/data/contentTypes/raw.binarysignal.jsonld
> +	"@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.raw.binarysignal",
no, that one is a panasonic specific raw image type

2021-10-12 12:37 UTC, apdavison commented on instances/data/contentTypes/python.jsonld
> +	"@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.python",
We may at least wish to distinguish Python 2 and Python 3. Even within Python 3, later versions add new syntax, so a script written with Python 3.10 features will not run with  Python 3.7.

2021-10-12 13:06 UTC, jagru20 commented on instances/data/contentTypes/blackrockmicrosystems.cerebus.jsonld
> +		".nsx"
I'll divide this up into a separate contenttype for each of the .nsx types named `application/vnd.blackrockmicrosystems.continuousdata.x` where x is replaced by the number in the respective extension. Moreover, I add the .nev contenttype as `blackrockmicrosystems.spikeinfo.jsonld`

2021-10-12 13:13 UTC, lzehl commented on instances/data/contentTypes/blackrockmicrosystems.cerebus.jsonld
> +		".nsx"
@jagru20 I think those would be better (because these are the full words of the abbreviations used for the extensions)
NSx: application/vnd.blackrockmicrosystems.neuroalsignals.x
NEV: application/vnd.blackrockmicrosystems.neuralevents

2021-10-12 13:33 UTC, jagru20 commented on instances/data/contentTypes/python.jsonld
> +	"@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.python",
ok, I see the point. I have no objections adding separate contenttypes for pythonfiles, I would do it in a manner of `application/vnd.python.2` or to distinguish further `application/vnd.python.23`, `application/vnd.python.31` etc. What do you think?

2021-10-12 13:35 UTC, lzehl commented on instances/data/contentTypes/python.jsonld
> +	"@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.python",
@apdavison I do not know, what do you think?

2021-10-12 13:35 UTC, jagru20 commented on instances/data/contentTypes/blackrockmicrosystems.cerebus.jsonld
> +		".nsx"
I agree. Is it `neuralsignals` or `neuronalsignals`? It's `neural` I suppose?

2021-10-12 13:38 UTC, lzehl commented on instances/data/contentTypes/blackrockmicrosystems.cerebus.jsonld
> +		".nsx"
@apdavison do you know ? would be the same for both `neural` or `neuronal` + `signals` OR `events` ??

2021-10-12 13:42 UTC, jagru20 commented on instances/data/contentTypes/blackrockmicrosystems.cerebus.jsonld
> +		".nsx"
I had a quick look at the specification, it is neural https://blackrockneurotech.com/research/wp-content/ifu/LB-0023-7.00_NEV_File_Format.pdf c.f. pages 3 and 16 respectively

2021-10-12 13:58 UTC, apdavison commented on instances/data/contentTypes/python.jsonld
> +	"@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.python",
There is an unofficial but widely used mediatype for Python code: `text/x-python`
I'd therefore go with `text/x-python`, `text/x-python.2`, `text/x-python.3`,  `text/x-python.2.7`, etc. I think it's better to keep the "." in the version identifiers.

2021-10-12 14:00 UTC, jagru20 commented on instances/data/contentTypes/python.jsonld
> +	"@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.python",
ok i'll then go with your suggestion.

2021-10-12 14:08 UTC, jagru20 commented on instances/data/contentTypes/python.jsonld
> +	"@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.python",
one problem that I have with the "x-" prefix though is that it is usually used to mark "experimental" contenttypes where "experimental" seems to mean "not IANA registered" would that mean, that we have to mark every not-IANA registered, type with that prefix? see also [matlab](https://github.com/HumanBrainProject/openMINDS_core/pull/216#discussion_r727060811)

2021-10-12 15:20 UTC, apdavison commented on instances/data/contentTypes/python.jsonld
> +	"@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.python",
That's complicated. My understanding is that use of the "x-" prefix has been deprecated, but where there are well-established media types with this prefix they can be retained.

2021-10-13 07:24 UTC, jagru20 commented on instances/data/contentTypes/python.jsonld
> +	"@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.python",
Ok so we keep it where it is used by now but do not introduce it for future types, right?

2021-10-13 07:46 UTC, jagru20 commented on instances/data/contentTypes/matlab.jsonld
> +	"@id": "https://openminds.ebrains.eu/instances/contentTypes/text/x-matlab",
We'll proceed as discussed [here](https://github.com/HumanBrainProject/openMINDS_core/pull/216#discussion_r727772112)

2021-10-15 09:16 UTC, lzehl requested changes
only some small issues. @apdavison can you also check again?

2021-10-15 09:16 UTC, lzehl commented on instances/data/contentTypes/blackrockmicrosystems.neuralevents.jsonld
> +    "Cerebus neural signal system"
I would add "Blackrock Neural Events"

2021-10-15 09:16 UTC, lzehl commented on instances/data/contentTypes/blackrockmicrosystems.neuralsignals.1.jsonld
> +	"Blackrock Neural Signal 1"
correct indent, change to "Blackrock Neural Signal**s** 1"

2021-10-15 09:16 UTC, lzehl commented on instances/data/contentTypes/blackrockmicrosystems.neuralsignals.2.jsonld
> +	"Blackrock Neural Signal 2"
correct indent, change to "Blackrock Neural Signals 2"

2021-10-15 09:16 UTC, lzehl commented on instances/data/contentTypes/blackrockmicrosystems.neuralsignals.3.jsonld
> +	"Blackrock Neural Signal 3"
correct indent, change to "Blackrock Neural Signals 3"

2021-10-15 09:16 UTC, lzehl commented on instances/data/contentTypes/blackrockmicrosystems.neuralsignals.4.jsonld
> +	"Blackrock Neural Signal 4"
correct indent, change to "Blackrock Neural Signals 4"

2021-10-15 09:16 UTC, lzehl commented on instances/data/contentTypes/blackrockmicrosystems.neuralsignals.5.jsonld
> +	"Blackrock Neural Signal 5"
correct indent, change to "Blackrock Neural Signals 5"

2021-10-15 09:16 UTC, lzehl commented on instances/data/contentTypes/blackrockmicrosystems.neuralsignals.6.jsonld
> +	"Blackrock Neural Signal 6"
correct indent, change to "Blackrock Neural Signals 6"

2021-10-15 09:16 UTC, lzehl commented on instances/data/contentTypes/blackrockmicrosystems.neuralsignals.7.jsonld
> +	"Blackrock Neural Signal 7"
correct indent, change to "Blackrock Neural Signals 7"
I did not know that this existed... what is different here?

2021-10-15 09:16 UTC, lzehl commented on instances/data/contentTypes/blackrockmicrosystems.neuralsignals.8.jsonld
> +	"Blackrock Neural Signal 8"
correct indent, change to "Blackrock Neural Signals 8"
I did not know that this existed... what is different here?

2021-10-15 09:16 UTC, lzehl commented on instances/data/contentTypes/blackrockmicrosystems.neuralsignals.9.jsonld
> +	"Blackrock Neural Signal 9"
correct indent, change to "Blackrock Neural Signals 9"
I did not know that this existed... what is different here?

2021-10-15 09:16 UTC, lzehl commented on instances/data/contentTypes/blackrockmicrosystems.x-parallelrecordings.jsonld
> +	"Blackrock Parallel Recordings"
correct indent

2021-10-15 09:16 UTC, lzehl commented on instances/data/contentTypes/x-ipynb+json.jsonld
> +	"@id": "https://openminds.ebrains.eu/instances/contentTypes/application/x-ipynb+json",
this is json based? I didn't know that :sweat_smile:

2021-10-15 09:16 UTC, lzehl commented on instances/data/contentTypes/x-matlab.jsonld
> +    "MATLAB"
correct indent

2021-10-15 09:22 UTC, jagru20 commented on instances/data/contentTypes/blackrockmicrosystems.neuralevents.jsonld
> +    "Cerebus neural signal system"
additionally also change "Cerebus neural signal system" to  "Cerebus neural event system"?

2021-10-15 09:24 UTC, lzehl commented on instances/data/contentTypes/blackrockmicrosystems.neuralevents.jsonld
> +    "Cerebus neural signal system"
yes, I guess that makes sense. I wasn't sure where you had that synonym from... I thought that might have been how Cerebus refers to it...

2021-10-15 09:29 UTC, jagru20 commented on instances/data/contentTypes/blackrockmicrosystems.neuralsignals.8.jsonld
> +	"Blackrock Neural Signal 8"
Same as for .ns9: in the specification ([link](https://blackrockneurotech.com/research/wp-content/ifu/LB-0023-7.00_NEV_File_Format.pdf)) it says on page 15: 

> In addition to the .NEV file described above, there can also be continuously sampled data files. These files have the extension .NSx where x is some number between 1 and 9. 

That's why they are in here.

2021-10-15 09:29 UTC, jagru20 commented on instances/data/contentTypes/blackrockmicrosystems.neuralsignals.9.jsonld
> +	"Blackrock Neural Signal 9"
Same as for .ns8: in the specification ([link](https://blackrockneurotech.com/research/wp-content/ifu/LB-0023-7.00_NEV_File_Format.pdf)) it says on page 15: 

> In addition to the .NEV file described above, there can also be continuously sampled data files. These files have the extension .NSx where x is some number between 1 and 9. 

That's why they are in here.

2021-10-15 09:33 UTC, jagru20 commented on instances/data/contentTypes/blackrockmicrosystems.neuralsignals.7.jsonld
> +	"Blackrock Neural Signal 7"
In the specification (link) it says on page 15:

    In addition to the .NEV file described above, there can also be continuously sampled data files. These files have the extension .NSx where x is some number between 1 and 9.

2021-10-15 09:38 UTC, jagru20 commented on instances/data/contentTypes/x-ipynb+json.jsonld
> +	"@id": "https://openminds.ebrains.eu/instances/contentTypes/application/x-ipynb+json",
😄 It actually is as the specification says: https://nbformat.readthedocs.io/en/latest/format_description.html 

I'll add that link to the jsonld and correct the indent.

2021-10-15 09:43 UTC, jagru20 commented on instances/data/contentTypes/blackrockmicrosystems.neuralevents.jsonld
> +    "Cerebus neural signal system"
I'll check that

2021-10-15 09:46 UTC, jagru20 commented on instances/data/contentTypes/blackrockmicrosystems.neuralevents.jsonld
> +    "Cerebus neural signal system"
As far as I can tell, this term refers to hardware rather than software, should we then delete it and only keep the blackrock-term? I think that would be clear enough. And I think .nsx and .nev should not share a synonym just because they are recorded by the same hardware.

2021-10-15 10:22 UTC, lzehl commented on instances/data/contentTypes/blackrockmicrosystems.neuralevents.jsonld
> +    "Cerebus neural signal system"
@jagru20 yes then delete it. We'll pick it up again once we gather hardware metadata ;)

2021-10-15 10:23 UTC, lzehl commented on instances/data/contentTypes/blackrockmicrosystems.neuralevents.jsonld
> +    "Cerebus neural signal system"
you mean deleting it for all blackrock formats correct?

2021-10-15 11:41 UTC, jagru20 commented on instances/data/contentTypes/blackrockmicrosystems.neuralevents.jsonld
> +    "Cerebus neural signal system"
yes, that's what I mean.

2021-10-15 11:44 UTC, lzehl commented on instances/data/contentTypes/blackrockmicrosystems.neuralevents.jsonld
> +    "Cerebus neural signal system"
:+1:

2021-10-25 08:01 UTC, lzehl approved these changes
Looks good to me. @jagru20 thanks for all this work you had with this large PR. 
@apdavison you think we can merge?

2021-10-25 11:50 UTC, apdavison approved these changes

2021-10-25 11:51 UTC, apdavison commented
Excellent work @jagru20 - ok to merge.

2021-10-25 11:55 UTC, jagru20 commented
thank you two for all the feedback and patience! And for the kind words.

2021-10-25 12:08 UTC, merged