Research updates (behavioralTask/protocol/protocolExecution)
openMetadataInitiative/openMINDS_core pull request #223
Opened 2021-08-24 09:12 UTC by UlrikeS91

Following a discussion with @lzehl  and @Peyman-N, we concluded on some updates for some of the `core/research` schemas:

 1. `behavioralTask` has been renamed to `behavioralProtocol`
 2. `studyOption` was removed from `protocol` since the `studyTarget` of the `protcolExecution` should cover this sufficiently
 3. A new schema, called `stimulation` has been added, which also has been added as property to both `behavioralProtocol` and `protocol` (in both cases with count 0 - N). This new schema has the following properties:
```
stimulationApproach | 1-1 | controlledTerms/stimulationApproach
stimulusType | 0 - 1 | controlledTerms/stimulusType  
```
`stimulationApproach` is similar to `experimentalApproach` giving an overarching type of stimulation/stimulus (e.g. auditory stimulus, electrical stimulus, etc.). @Peyman-N has added this as `stimulusModality` to the `controlledTerms` schemas. @Peyman-N, @lzehl and @apdavison, if you think that `stimulusModality` is more suitable than `stimulationApproach`, please let me know and I'll change it. 
`stimulusType` is similar to `technique` giving a more specific type of stimulus (e.g. direct current, static grating, etc.).  

@olinux FYI

2021-08-24 17:31 UTC, lzehl requested changes

2021-08-24 17:31 UTC, lzehl commented on schemas/research/stimulation.schema.tpl.json
> +    "stimulationApproach"
let's make type also a required one

2021-08-25 08:53 UTC, UlrikeS91 commented on schemas/research/stimulation.schema.tpl.json
> +    "stimulationApproach"
done

2021-08-25 09:58 UTC, lzehl approved these changes

2021-08-25 09:59 UTC, merged