TissueSample(Collection) updates
openMetadataInitiative/openMINDS_core pull request #229
Opened 2021-09-06 11:36 UTC by UlrikeS91

Intro of "descendedFrom" to TissueSample and TissueSampleCollection (pointing to all specimen states as options).

2021-09-06 14:03 UTC, lzehl requested changes

2021-09-06 14:03 UTC, lzehl commented on schemas/research/tissueSample.schema.tpl.json
> +      "_instruction": "Add all specimen states used to produce or obtain this tissue sample from.",
delete "from"

2021-09-06 14:03 UTC, lzehl commented on schemas/research/tissueSampleCollection.schema.tpl.json
> +      "_instruction": "Add all specimen states used to produce or obtain this tissue sample collection from.",
delete "from"

2021-09-07 06:08 UTC, UlrikeS91 commented on schemas/research/tissueSample.schema.tpl.json
> +      "_instruction": "Add all specimen states used to produce or obtain this tissue sample from.",
done

2021-09-07 06:08 UTC, UlrikeS91 commented on schemas/research/tissueSampleCollection.schema.tpl.json
> +      "_instruction": "Add all specimen states used to produce or obtain this tissue sample collection from.",
done

2021-09-07 08:03 UTC, lzehl approved these changes

2021-09-07 08:03 UTC, merged