adding contentType for JSONLD
openMetadataInitiative/openMINDS_core pull request #266
Opened 2021-11-20 13:36 UTC by lzehl

please double check the IANA reference

2022-01-06 14:55 UTC, lzehl commented
@apdavison is this ready to be merged?

2022-01-10 11:38 UTC, apdavison requested changes

2022-01-10 11:38 UTC, apdavison commented on instances/data/contentTypes/ld+json.jsonld
> +	    "JSONLD"
I think the synonym should be "JSON-LD", it's written that way almost everywhere.

2022-01-10 13:03 UTC, lzehl commented on instances/data/contentTypes/ld+json.jsonld
> +	    "JSONLD"
done :)

2022-01-10 13:31 UTC, apdavison approved these changes

2022-01-10 13:31 UTC, merged