Create odml.jsonld
openMetadataInitiative/openMINDS_core pull request #269
Opened 2021-11-28 14:10 UTC by lzehl

2021-11-28 14:11 UTC, lzehl commented
@apdavison OR @jagru20 I think it is enough if one of you reviews this PR. whoever is faster ;)

2021-11-29 09:22 UTC, jagru20 requested changes
I suggest naming it `application/vnd.g-node.odml` because it seems to be introduced and maintained by G-Node, right?

2021-11-29 09:22 UTC, jagru20 commented on instances/data/contentTypes/odml.jsonld
> +	"@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.odml",
otherwise, if the specification is introduced/maintained by G-Node as the "specification" property's value suggests, I would use ``application/vnd.g-node.odml``

2021-11-29 09:22 UTC, jagru20 commented on instances/data/contentTypes/odml.jsonld
> +	"name": "application/vnd.odml",
see above

2021-11-29 09:25 UTC, lzehl commented on instances/data/contentTypes/odml.jsonld
> +	"@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.odml",
yes. good point. done

2021-11-29 09:25 UTC, lzehl commented on instances/data/contentTypes/odml.jsonld
> +	"name": "application/vnd.odml",
done

2021-11-29 10:41 UTC, jagru20 approved these changes

2021-11-29 10:43 UTC, lzehl commented
@jagru20 feel free to merge (@apdavison that's okay, no?)

2021-11-29 13:28 UTC, jagru20 commented
one more thing that I just noticed: shouldn't this PR go against the v4 branch?

2021-11-29 13:49 UTC, merged