Adding Device to core
openMetadataInitiative/openMINDS_core pull request #270
Opened 2021-11-29 13:57 UTC by Peyman-N

As we have discussed in issue #230. I am consolidating the `device` from openMINDS-ephys and `hardware` from openMINDS-computation into the openMINDS-core. 
To do so I am introducing two schema, `hardware` and `hardwareVersion`.
Most of the properties in `hardwareVersion` is the same as the properties proposed  in issue #230 by @lzehl. 
Only `manufacturer` and `deviceType` have been moved into `hardware` as I think if any of these two changes we are dealing with a new hardware and not a new version of the existant hardware. And I have added `modelName` in an effort to capture some of these changes. It can be argued that the model name should be moved to `hardware` too but I let @apdavison and @lzehl to decide it should be in `hardwareVersion` or in `hardware`.

2021-11-30 09:27 UTC, jcolomb commented
I wonder how you will define self-made hardware (which is probably the default in ephys) ? would you want to enter every parts of the setup using the schema ? These do not have a manufacturer by the way.

Also you have a software entry, it is not clear whether you mean firmware (software running on the hardware) or some data acquisition software (spike2 for instance), or both.

I would also add a "digitalIdentifier" component, accepting doi and rrid.

2021-11-30 11:45 UTC, Peyman-N commented
@jcolomb thanks for the comment. 

> I wonder how you will define self-made hardware (which is probably the default in ephys) ? would you want to enter every parts of the setup using the schema ? These do not have a manufacturer by the way.

We plan to handle this by introducing another schema called `setup` and `setupVersion`. See #271 

> Also you have a software entry, it is not clear whether you mean firmware (software running on the hardware) or some data acquisition software (spike2 for instance), or both.

I meant both of them, for that propose I didn't specify in the instruction. Personally I think if the firmware changes, we should create a new hardwareVersion for this new hardware. 

> I would also add a "digitalIdentifier" component, accepting doi and rrid.

I completely agree that, my original draft had it, but it seemed extensive to have so many identification properties (short name, long name, digitalIdentifier). Anyway, if large enough number of the hardwares have already assigned these, it is a good idea to have it.

2021-11-30 11:45 UTC, lzehl commented
@Peyman-N I'm not sure I will find the time soon to review this PR. I hope it can wait a bit?

2021-11-30 12:36 UTC, apdavison commented
@lzehl yes, it can wait a bit, we can start migrating the in-depth ephys metadata using the current openMINDS/ephys draft (which contains Device), then fix things up once Device appears in core.

2022-03-23 14:56 UTC, lzehl commented
@Peyman-N I suggest to merge the Hardware/HardwareVersion to one schema. Feel free to replace them with the Device schema from the ephys extension. Comments for ephys/Device which I would probably rename to HardwareModel:

+ **manufacturer** should be optional or you need to clarify in the instruction that if it is self-made to just state "custom-made" or something like this
+ **modelName** (required) should be the full name of this particular model as stated from the manufacturer 
+ **modelIdentifier** (optional) (array) should allow RRID (or DOI? others?) as an external source to identify this particular model
+ **internalIdentifier** not relevant for all (make it optional)
+ **software** instructions need to be better, suggestion: "Add all software versions that can control this hardware model." (note that this will require us to register many hardware control software for EBRAINS)
+ **parameterSet** this can actually only be non-changeable hardware parameters (e.g., filters) changeable hardware parameters need to be covered in an execution. Suggestion: rename to "fixedHardwareSettings" and change instructions to "Add the non-changeable hardware parameters for this hardware model." change embeddedTypes to NumericalParameter and StringParamter (parameter set requires a relevant for which is clear in this context, because its the hardware model itself).

2022-03-23 14:56 UTC, lzehl requested changes
see previous comment

2022-03-24 10:00 UTC, jcolomb commented
hello, 
You might want to check https://www.rd-alliance.org/groups/persistent-identification-instruments-wg and their schema. They created a metadata format and will mint doi for instrument (i.e. the physical hardware itself is getting a doi, not its description). see schema at https://github.com/rdawg-pidinst/schema/blob/master/schema.rst

2022-03-24 13:11 UTC, Peyman-N commented
@lzehl I applied the changes, please review it again.

2022-03-24 13:15 UTC, Peyman-N commented
@jcolomb thanks a lot for your comment, it seems like they are gathering quite extensive amount of information. Maybe we can redirect the wiling authors to them and register the ID given to them by rd-alliance.

2022-03-24 13:31 UTC, jcolomb reviewed
trying to make compatibility with https://github.com/rdawg-pidinst/schema/blob/master/schema.rst#identtype more obvious

2022-03-24 13:31 UTC, jcolomb commented on schemas/products/hardwareModel.schema.tpl.json
> +        "manufacturer": {
```suggestion
        "manufacturerName": {
```

2022-03-24 13:31 UTC, jcolomb commented on schemas/products/hardwareModel.schema.tpl.json
> +        },
```suggestion
        "AlternateIdentifier": {
            "type": "string",
            "_instruction": "inventory number or serial number specific for the model, provided by the manufacturer or institution."
        },
```
should this be an array to make serial number + inventory number possible ?

2022-03-24 13:31 UTC, jcolomb commented on schemas/products/hardwareModel.schema.tpl.json
> +        "manufacturer",
```suggestion
        "manufacturerName",
```

2022-03-24 13:32 UTC, jcolomb commented
@Peyman-N sounds like a good plan, wonder about some of the mandatory field there, should they be there:
- owner 
- landing page

+ see comment in the files about some entry files.

2022-03-24 13:49 UTC, lzehl commented on schemas/products/hardwareModel.schema.tpl.json
> +        "manufacturer": {
I agree this is more precise

2022-03-24 13:53 UTC, lzehl commented on schemas/products/hardwareModel.schema.tpl.json
> +        },
or maybe even "identificationNumber"'? if we make it an array, SerialNumer and InventoryNumber should probably become their own instance (as the other digital identifer). It is a valid argument to allow both @Peyman-N / @apdavison your view?

2022-03-24 13:53 UTC, lzehl commented on schemas/products/hardwareModel.schema.tpl.json
> +        "manufacturer",
agreed (see previous comment)

2022-03-24 13:58 UTC, lzehl commented on schemas/products/hardwareModel.schema.tpl.json
> +        },
looking through the other schema again it should be : "manufacturerIdentifier" for serial number. if inventory number is chosen by the owner it is the "internalIdentifier" for openMINDS

2022-03-24 13:59 UTC, lzehl commented
@jcolomb and @Peyman-N "owner" is definitely a good field to add for hardware (pointing to Person AND OR Organization; should be an array I think, because multiple owners are possible)

2022-03-24 15:21 UTC, Peyman-N commented on schemas/products/hardwareModel.schema.tpl.json
> +        },
I agree that the `internalIdentifier` and `InventoryNumber` are strongly related, but I see some cases that these two are different. Using the `InventoryNumber` in the data is not that common, as it is more for administrative purposes. But its advantage is that it is mostly unique. Anyway I argue `internalIdentifier` should be there while `InventoryNumber` is a nice to have.

2022-03-24 15:25 UTC, Peyman-N commented
@lzehl @jcolomb I agree that `owner` is really important to have, actually in openMINDS-MRI, the MRI machine has this attached to it. As in MRI datasets, we can see lots of multi-center data, I didn't thought it would be important for other devices too.

2022-03-28 07:28 UTC, lzehl requested changes
@Peyman-N : please add "owner" as an optional property with `"type": "array"` and "_linkedTypes": ["https://openminds.ebrains.eu/core/Person", "https://openminds.ebrains.eu/core/Organization"]

@apdavison with the other small updates, this seems mature to me to be merged. Do you agree?

2022-03-28 07:28 UTC, lzehl commented on schemas/products/hardwareModel.schema.tpl.json
> +            "_instruction": "The full name of this particular model as stated from the manufacturer."
or institution (because also self-made devices could get general model names)

2022-03-28 07:28 UTC, lzehl commented on schemas/products/hardwareModel.schema.tpl.json
> +        },
then add "inventoryNumber" as an optional property

2022-03-28 07:28 UTC, lzehl commented on schemas/products/hardwareModel.schema.tpl.json
> +        },
description suggestion: "Add the institutional inventory number (if it differs from the internal identifier)."

2022-03-28 09:26 UTC, apdavison requested changes
- I don't think "HardwareModel" is a good name for this.

  1. we wish to represent an individual piece of hardware, an individual device. A "hardware model" is a description of the idealised, Platonic device, and/or of the entire collection of such near-identical devices ever manufactured.

  2. the word "model" means too many things, and I think there is a risk of confusion with Model and ModelVersion, so where possible we should avoid it.

How about calling this schema "ManufacturedDevice", or just keep "Device"?

- thinking about a hardware system such as the JUSUF supercomputer, can we use this schema to represent such an entity? I think so, but then it would be nice to have a "hasComponent" field, linking to the same schema, so we can describe the processors, memory, storage, etc. Alternatively, the Setup schema might be more appropriate for that? (maybe with the name "HardwareSystem")

2022-03-28 09:26 UTC, apdavison commented on schemas/products/hardwareModel.schema.tpl.json
> +    "_type": "https://openminds.ebrains.eu/ephys/HardwareModel",
should be "core", not "ephys"

2022-03-28 09:26 UTC, apdavison commented on schemas/products/hardwareModel.schema.tpl.json
> +        "deviceType": {
I think we should use either "device" or "hardware", but we shouldn't mix the two.

2022-03-28 09:26 UTC, apdavison commented on schemas/products/hardwareModel.schema.tpl.json
> +            "_instruction": "Enter the identifier of this Device that is used within the corresponding data."
"within the corresponding data" doesn't seem to fit here. The instruction should make it clear how "internalIdentifier" differs from the other identifiers.

2022-03-28 09:26 UTC, apdavison commented on schemas/products/hardwareModel.schema.tpl.json
> +        "manufacturerName": {
I think this field should be "manufacturer" and link to an array of Organizations/Persons. If a device is custom-made, we may wish to know who made it, and what their affiliation is.

2022-03-28 09:26 UTC, apdavison commented on schemas/products/hardwareModel.schema.tpl.json
> +            "_instruction": "The full name of this particular model as stated from the manufacturer."
if we make manufacturer a link to Person/Organization, we don't need to specify institution here.

2022-03-28 09:26 UTC, apdavison commented on schemas/products/hardwareModel.schema.tpl.json
> +        "fixedHardwareSettings": {
"settings" is not a good name when this schema is used for devices. A glass electrode doesn't have settings. How about "hardwareProperties"? I think that name fits well enough for _fixed_ settings of electronic devices as well.

2022-03-28 09:34 UTC, lzehl commented on schemas/products/hardwareModel.schema.tpl.json
> +    "_type": "https://openminds.ebrains.eu/ephys/HardwareModel",
yes. overlooked that one.

2022-03-28 09:34 UTC, lzehl commented on schemas/products/hardwareModel.schema.tpl.json
> +        "deviceType": {
I agree. If we go with "Device" for the schema name stick to "device"

2022-03-28 09:35 UTC, lzehl commented
@Peyman-N & @apdavison 
+ naming the Schema Device sounds good to me. 
+ if we do not need an option for hardware systems immediately, I suggest we postpone this discussion. If we need it, I would probably tend to solve it via a "HardwareSystem" schema
+ see direct comments to @apdavison feedback

2022-03-28 09:39 UTC, lzehl commented on schemas/products/hardwareModel.schema.tpl.json
> +            "_instruction": "Enter the identifier of this Device that is used within the corresponding data."
Suggestion: "Enter the identifier of this device that is used by the operators in reports, documentation or data annotation."

2022-03-28 09:40 UTC, lzehl commented on schemas/products/hardwareModel.schema.tpl.json
> +        "manufacturerName": {
sounds good to me

2022-03-28 09:40 UTC, lzehl commented on schemas/products/hardwareModel.schema.tpl.json
> +            "_instruction": "The full name of this particular model as stated from the manufacturer."
yes. I agree

2022-03-28 09:41 UTC, lzehl commented on schemas/products/hardwareModel.schema.tpl.json
> +        "fixedHardwareSettings": {
okay. sounds good. it anyway will be a curation effort to make sure that no variable properties are mentioned here.

2022-04-08 09:02 UTC, Peyman-N commented on schemas/products/hardwareModel.schema.tpl.json
> +        "fixedHardwareSettings": {
As we are adopting device for schema name I am using `deviceProperties` for the name of this property.

2022-04-08 09:03 UTC, Peyman-N commented on schemas/products/hardwareModel.schema.tpl.json
> +        "fixedHardwareSettings": {
As we are naming the schema `device`, I am using `deviceProperties` for the name of this property.

2022-04-11 14:46 UTC, lzehl requested changes
Note: Person and Organizations can never be linked as "_embeddedTypes"

General openMINDS conventions:
+ property names are typically stated in their singular form (not plural)
+ instructions for "_linkedTypes"/"_embeddedTypes" start with "Add ..."
+ instructions for other value types (e.g. string, integer etc) start with "Enter ..."

2022-04-11 14:46 UTC, lzehl commented on schemas/products/device.schema.tpl.json
> +            "_instruction": "Reference to a device type",
"Add the generic type of this device."

2022-04-11 14:46 UTC, lzehl commented on schemas/products/device.schema.tpl.json
> +            "_instruction": "The manufacturer or supplier providing the item. If it is self-made please state the name of the person that manufactures it.",
"Add the private or industrial vendor (person or organization) that manufactured this device."

2022-04-11 14:46 UTC, lzehl commented on schemas/products/device.schema.tpl.json
> +            "_instruction": "The full name of this particular model as stated from the manufacturer."
"Enter the full name of this particular model as stated from the manufacturer."

2022-04-11 14:46 UTC, lzehl commented on schemas/products/device.schema.tpl.json
> +            "_instruction": "Please indicate any persistent identifier asosiated with this device",
"Add any persistent identifier assigned to this device."

2022-04-11 14:46 UTC, lzehl commented on schemas/products/device.schema.tpl.json
> +            "_instruction": "specific for the model, provided by the manufacturer or institution."
"Enter the serial number of this device."

2022-04-11 14:46 UTC, lzehl commented on schemas/products/device.schema.tpl.json
> +            "_embeddedTypes": [
"_linkedTypes"

2022-04-11 14:46 UTC, lzehl commented on schemas/products/device.schema.tpl.json
> +            "_instruction": "Institution(s) or person responsible for the management of the instrument. This may include the legal owner, the operator, or an institute providing access to the instrum
"Add all legal owners (person or organization) of this device."

2022-04-11 14:46 UTC, lzehl commented on schemas/products/device.schema.tpl.json
> +            "_embeddedTypes": [
"_linkedTypes"

2022-04-11 14:46 UTC, lzehl commented on schemas/products/device.schema.tpl.json
> +            "_instruction": "Add the institutional inventory number (if it differs from the internal identifier)."
"Enter the institutional inventory number (if it differs from the internal identifier)."

2022-04-11 14:46 UTC, lzehl commented on schemas/products/device.schema.tpl.json
> +        "deviceProperties": {
"deviceProperty"

2022-04-11 14:46 UTC, lzehl commented on schemas/products/device.schema.tpl.json
> +            "_instruction": "Add the non-changeable device property for this device.",
"Add all non-changeable device properties for this device."

2022-04-11 14:46 UTC, lzehl commented on schemas/products/device.schema.tpl.json
> +        "deviceProperties": {
(property names are by convention singular in openMINDS)

2022-06-15 10:50 UTC, lzehl requested changes
@Peyman-N this PR is nearly ready to be merged. Only some small description updates left (@apdavison feel free to correct my suggestions).

2022-06-15 10:50 UTC, lzehl commented on schemas/products/device.schema.tpl.json
> +            "_instruction": "Add the private or industrial vendor (person or organization) that manufactured this device.",
"Add the private or industrial manufacturer (person or organization) that constructed this device."

2022-06-15 10:50 UTC, lzehl commented on schemas/products/device.schema.tpl.json
> +            "_instruction": "Enter the full name of this particular model as stated from the manufacturer."
"Enter the full name of the particular model of this device (as it is defined by the manufacturer)."

2022-06-15 10:50 UTC, lzehl commented on schemas/products/device.schema.tpl.json
> +            "_instruction": "Add any persistent identifier assigned to this device.",
"Add any digital, persistent and universal unique identifier assigned to this device."

-> rename to "digitalIdentifier" ?

2022-06-21 07:53 UTC, lzehl approved these changes

2022-06-21 07:54 UTC, lzehl commented
@UlrikeS91 & @apdavison could you have another look ? From my side we can merge it

2022-06-29 12:27 UTC, apdavison commented
looks good to me.

2022-07-21 09:58 UTC, UlrikeS91 requested changes
@lzehl and I have worked on this together 

@Peyman-N and @apdavison, what do you think? In particular, in respect to this issue: https://github.com/HumanBrainProject/openMINDS_ephys/issues/20#issuecomment-1156521847?

2022-07-21 09:58 UTC, UlrikeS91 commented on schemas/products/device.schema.tpl.json
> +        "modelName"
not sure if this should be required

2022-07-21 09:58 UTC, UlrikeS91 commented on schemas/products/device.schema.tpl.json
> +        },
since setup should get "components" linking to both software and hardware, software needs to be removed from the Device schema

also solves the issue that not all devices have a software, e.g. electrodes or pipettes

2022-07-21 09:58 UTC, UlrikeS91 commented on schemas/products/device.schema.tpl.json
> +        }
Generally, the parameters have to be updated to the new system (NumericalParameter --> NumericalProperty and StringParameter --> StringProperty).

We should remove the deviceProperty complete and rather add a property for the specific information about the device type, called "attribute" (optional) linking to attribute schemas for each of the device types, e.g. ElectrodeAttribute. These specific schemas would then include the device properties. Linking to attribute schemas for each device type instead of defining specific device schemas is more elegant because we do not have to replace generic devices to register the more specific information later on. 

Every property that is usage dependent for the device (aka changing properties) should be defined in something similar to what we done for specimen and their states. In this case it could be called something like "usedSetting" (cf. https://github.com/HumanBrainProject/openMINDS_ephys/issues/20#issuecomment-1156521847). 

**ELECTRODE** 
**setting**
_expected/defined key-value pairs:_
internalIdentifier
electrode contact (point + impedance)
_custom key-value pairs (called "additionalProperty" like we did it for the activity schemas):_
numericalProperty
stringProperty

**attribute** 
_expected/defined key-value pairs:_
length
number of contact points
shape
material
_custom key-value pairs (like deviceProperty but called "additionalProperty" like we did it for the activity schemas):_
numericalProperty
stringProperty

2022-07-26 19:20 UTC, lzehl commented
Based on the discussion we (@apdavison , @Peyman-N , @lzehl ) had offline, we decided to have only specific device schemas. This means that the current device schema needs to be reduced to the common properties and changed into a concept schema (which cannot be used directly) which will be extended by specific device schemas (e.g. Electrode).

concept device schema
```json
{
    "required": [
        "manufacturer",
        "modelName"
    ],
    "properties": {
        "description": {
            "type": "string",
            "_instruction": "Enter a description of this device."
        },
        "digitalIdentifier": {
            "_instruction": "Add any digital, persistent and universal unique identifier assigned to this device.",
            "_linkedTypes": [
                "https://openminds.ebrains.eu/core/DOI",
                "https://openminds.ebrains.eu/core/RRID"
            ]
        },
        "factoryIdentifier": {
            "type": "string",
            "_instruction": "Enter the identifier as defined by the manufacturer."
        },
        "inventoryNumber": {
            "type": "string",
            "_instruction": "Enter the institutional inventory number."
        },
       "lookupLabel": {
            "type": "string",
            "_instruction": "Enter a lookup label for this device that may help you to more easily find it again."
        },
        "manufacturer": {
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "_instruction": "Add the private or industrial manufacturer (person or organization) that constructed this device.",
            "_linkedCategories": [
                "legalPerson"
            ]
        },
        "name": {
            "type": "string",
            "_instruction": "Enter the name this particular device, preferably the model name as defined by the manufacturer."
        },
        "owner": {
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "_instruction": "Add all legal owners (person or organization) of this device.",
            "_linkedCategories": [
                "legalPerson"
            ]
        },
        "serialNumber": {
            "type": "string",
            "_instruction": "Enter the serial number of this device."
        }
    }
}
```

There are two options for the location of the specific device schemas:
(a) we open a device/ folder in core and collect here all devices used across extensions
(b) we open a device/ folder in each extension (if needed) and collect here the devices that are mostly used by the extension
@Peyman-N @apdavison : what would you prefer? I do not have a preference.

@Peyman-N @apdavison : "usedSetting" + linked schemas (mentioned below) which will contain all properties of the specific device that are usage dependent can also be called differently. I'm open for suggestions.

@apdavison  @Peyman-N : we need to discuss again what we define as an electrode and what we define as an electrode array.
+ we could define that an electrode equals a single conductive contact, instead of a structure that can have one or multiple contacts
+ for electrode array we can maybe have a look at this paper: https://www.biorxiv.org/content/10.1101/2021.01.24.427975v1.full

@Peyman-N : we can discuss and modify the properties listed below together in our meeting tomorrow (the provided lists are incomplete and not discussed)

**Electrode schema** with device properties (see above) + specific properties:
+ shape -> fitting shape schema from SANDS ?
+ insulatorMaterial -> MolecularEntity
+ conductorMaterial -> MolecularEntity
+ contact -> Contact (quantity == 1?)
+ factoryResistance -> QV or QVR
+ usedSetting -> ElectrodeSetting

**ElectrodeSetting schema**:
+ internalIdentifier
+ resistance -> QV or QVR

**Pipette schema** with device properties (see above) + specific properties:
+ shape -> fitting shape shape schema from SANDS ?
+ factoryResistance -> QV or QVR
+ usedSetting -> PipetteSetting

**PipetteSetting schema:
+ internalIdentifier
+ resistance -> QV or QVR
+ solution -> chemicals/Solution ( not sure how we named that now...)

2022-09-19 13:26 UTC, UlrikeS91 commented
Conclusion from an offline meeting with @apdavison @Peyman-N and @lzehl: 

> concept device schema
> 
> ```json
> {
>     "required": [
>         "manufacturer",
>         "modelName"
>     ],
>     "properties": {
>         "description": {
>             "type": "string",
>             "_instruction": "Enter a description of this device."
>         },
>         "digitalIdentifier": {
>             "_instruction": "Add any digital, persistent and universal unique identifier assigned to this device.",
>             "_linkedTypes": [
>                 "https://openminds.ebrains.eu/core/DOI",
>                 "https://openminds.ebrains.eu/core/RRID"
>             ]
>         },
>         "factoryIdentifier": {
>             "type": "string",
>             "_instruction": "Enter the identifier as defined by the manufacturer."
>         },
>         "inventoryNumber": {
>             "type": "string",
>             "_instruction": "Enter the institutional inventory number."
>         },
>        "lookupLabel": {
>             "type": "string",
>             "_instruction": "Enter a lookup label for this device that may help you to more easily find it again."
>         },
>         "manufacturer": {
>             "type": "array",
>             "minItems": 1,
>             "uniqueItems": true,
>             "_instruction": "Add the private or industrial manufacturer (person or organization) that constructed this device.",
>             "_linkedCategories": [
>                 "legalPerson"
>             ]
>         },
>         "name": {
>             "type": "string",
>             "_instruction": "Enter the name this particular device, preferably the model name as defined by the manufacturer."
>         },
>         "owner": {
>             "type": "array",
>             "minItems": 1,
>             "uniqueItems": true,
>             "_instruction": "Add all legal owners (person or organization) of this device.",
>             "_linkedCategories": [
>                 "legalPerson"
>             ]
>         },
>         "serialNumber": {
>             "type": "string",
>             "_instruction": "Enter the serial number of this device."
>         }
>     }
> }
> ```

- keep "serial number"
- remove "factory identifier" and "inventory number"
- add "deviceType" again 


> There are two options for the location of the specific device schemas: (a) we open a device/ folder in core and collect here all devices used across extensions (b) we open a device/ folder in each extension (if needed) and collect here the devices that are mostly used by the extension @Peyman-N @apdavison : what would you prefer? I do not have a preference.

We go with option B (until/if we ever come across a case that should be used across extensions, then it will be moved to core). We will keep them in each extension in a dedicated folder called "device".


> @Peyman-N @apdavison : "usedSetting" + linked schemas (mentioned below) which will contain all properties of the specific device that are usage dependent can also be called differently. I'm open for suggestions.

Two schemas: one for the "Usage" (aka State) and one for "Device", where usage points to device with a property called "device". 


> @apdavison @Peyman-N : we need to discuss again what we define as an electrode and what we define as an electrode array.
> 
> * we could define that an electrode equals a single conductive contact, instead of a structure that can have one or multiple contacts
> * for electrode array we can maybe have a look at this paper: https://www.biorxiv.org/content/10.1101/2021.01.24.427975v1.full

Electrode == one contact  
Electrode array == array of multiple contacts


> @Peyman-N : we can discuss and modify the properties listed below together in our meeting tomorrow (the provided lists are incomplete and not discussed)
> 
> **Electrode schema** with device properties (see above) + specific properties:
> 
> * shape -> fitting shape schema from SANDS ?
> * insulatorMaterial -> MolecularEntity
> * conductorMaterial -> MolecularEntity
> * contact -> Contact (quantity == 1?)
> * factoryResistance -> QV or QVR
> * usedSetting -> ElectrodeSetting
> 
> **ElectrodeSetting schema**:
> 
> * internalIdentifier
> * resistance -> QV or QVR
> 
> **Pipette schema** with device properties (see above) + specific properties:
> 
> * shape -> fitting shape shape schema from SANDS ?
> * factoryResistance -> QV or QVR
> * usedSetting -> PipetteSetting
> 
> **PipetteSetting schema:
> 
> * internalIdentifier
> * resistance -> QV or QVR
> * solution -> chemicals/Solution ( not sure how we named that now...)

Detailed feedback postponed until PR is made. 

Additionally:
@apdavison: Make hardware system in computation the extension of device

2022-09-19 14:11 UTC, UlrikeS91 approved these changes

2022-09-19 14:11 UTC, apdavison approved these changes

2022-09-19 14:11 UTC, lzehl approved these changes

2022-09-19 14:12 UTC, merged