Moving measurement to core
openMetadataInitiative/openMINDS_core pull request #273
Opened 2021-11-30 14:43 UTC by Peyman-N

This pull request moves the `measurement` schema from the openMINDS-ephys to the openMINDS-core. 
Measurement schema is meant to capture a single and isolate measurement. More complex measurements should be handelle by core/recording see #272

2022-07-21 08:31 UTC, lzehl requested changes
@UlrikeS91 and @lzehl reviewed together

2022-07-21 08:31 UTC, lzehl commented on schemas/data/measurement.schema.tpl.json
> +}
There needs to be a newline at the end of JSONs.

2022-07-21 08:31 UTC, lzehl commented on schemas/data/measurement.schema.tpl.json
> +            "_linkedTypes": [
Reduce to type /core/Device (reason will become clear with feedback for /core/Device PR #270 )

2022-07-26 09:38 UTC, lzehl requested changes

2022-07-26 09:38 UTC, lzehl commented on schemas/data/measurement.schema.tpl.json
> +        "measurementType"
this is not the correct name of the property. I think you mean "measuredQuantity" correct?

2022-09-19 11:05 UTC, Peyman-N commented on schemas/data/measurement.schema.tpl.json
> +        "measurementType"
Yes

2022-09-19 15:17 UTC, lzehl approved these changes

2022-09-19 15:17 UTC, lzehl commented on schemas/data/measurement.schema.tpl.json
> +        "device": {
needs to link to the all possible deviceUsage schemas. (-> intro of category: deviceUsage)

2022-09-19 15:17 UTC, lzehl commented on schemas/data/measurement.schema.tpl.json
> +        "description": {
change to "additionalRemarks"

2022-09-19 15:24 UTC, lzehl approved these changes

2022-09-19 15:25 UTC, UlrikeS91 approved these changes

2022-09-19 15:25 UTC, apdavison approved these changes

2022-09-19 15:25 UTC, merged