Create ELAN content types
openMetadataInitiative/openMINDS_core pull request #276
Opened 2021-12-16 12:54 UTC by lzehl

ELAN content types:
+ vnd.elan.event (.pos)
+ vnd.elan.continuous-data (.eeg + .eeg.ent)

2021-12-16 15:33 UTC, jagru20 requested changes
This PR should go into v4, right? We should change the default branch.

2021-12-16 15:33 UTC, jagru20 commented on instances/data/contentTypes/elan.continuous-data.jsonld
> +}
does this file extend or replace the existing elan contenttype?

2021-12-16 16:26 UTC, lzehl commented on instances/data/contentTypes/elan.continuous-data.jsonld
> +}
replace.

2021-12-16 16:27 UTC, lzehl commented on instances/data/contentTypes/elan.continuous-data.jsonld
> +}
well. one replaces the other is an additional elan content type

2021-12-16 16:27 UTC, lzehl commented
> 

damn... yes we should really change it now.

2021-12-16 16:30 UTC, lzehl commented
@jagru20 I've changed the base. Something else I missed?

2021-12-16 16:34 UTC, jagru20 commented on instances/data/contentTypes/elan.continuous-data.jsonld
> +}
@lzehl  did you see this?

2021-12-16 16:52 UTC, lzehl commented on instances/data/contentTypes/elan.continuous-data.jsonld
> +}
what do you mean?

2021-12-16 17:48 UTC, jagru20 commented on instances/data/contentTypes/elan.continuous-data.jsonld
> +}
oh it did not display your response, while i was writing that. next time I'll refresh the page before commenting :D

2021-12-16 17:48 UTC, jagru20 commented on instances/data/contentTypes/elan.continuous-data.jsonld
> +}
However, then the other file needs to be deleted

2021-12-16 17:51 UTC, jagru20 approved these changes

2021-12-16 18:34 UTC, lzehl commented
@jagru20 thank you for taking care of deleting the existing one... I completely overlooked (and actually thought I modified the existing one...) Should I merge then?

2022-01-06 14:54 UTC, lzehl commented
@jagru20 can we merge this one?

2022-01-06 15:10 UTC, jagru20 commented
sorry, I missed that last comment! yes we can merge it.

2022-01-06 16:29 UTC, merged