Add more Neo input types
openMetadataInitiative/openMINDS_core pull request #299
Opened 2022-02-03 12:10 UTC by JuliaSprenger

This PR is extending the list of content types based on input files of the [Neo](https://github.com/NeuralEnsemble/python-neo/) package.
@lzehl @apdavison What do you think?

2022-02-03 14:04 UTC, lzehl requested changes
@JuliaSprenger thanks a lot for this PR :) I made a few comments.

I think some of the CTs are already registered / are duplicates (please double check, I hope I catched all).

@apdavison your feedback will be needed here as well (see my comments).

2022-02-03 14:04 UTC, lzehl commented on instances/data/contentTypes/alphaomega0.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.alphaomega0-eng",
this should be evaluated together with potential changes for https://github.com/HumanBrainProject/openMINDS_core/blob/v4/instances/data/contentTypes/alphaomega.jsonld

2022-02-03 14:04 UTC, lzehl commented on instances/data/contentTypes/alphaomega0.jsonld
> +  "synonym": [
set it to null if you don't know a synonym.

2022-02-03 14:04 UTC, lzehl commented on instances/data/contentTypes/biocam.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.biocam",
should be the same as the name at the end (vnd.biocam+hdf)

2022-02-03 14:04 UTC, lzehl commented on instances/data/contentTypes/biocam.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.biocam",
similar for filename: should be biocam+hdf.jsonld

2022-02-03 14:04 UTC, lzehl commented on instances/data/contentTypes/brainwaredam.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.brainwaredam",
same as: https://github.com/HumanBrainProject/openMINDS_core/blob/v4/instances/data/contentTypes/hyland.brainwaredam.jsonld
??

2022-02-03 14:04 UTC, lzehl commented on instances/data/contentTypes/brainwaref32.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.brainwaref32",
same as https://github.com/HumanBrainProject/openMINDS_core/blob/v4/instances/data/contentTypes/hyland.brainwaref32.jsonld ??

2022-02-03 14:04 UTC, lzehl commented on instances/data/contentTypes/brainwaresrc.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.brainwaresrc",
same as https://github.com/HumanBrainProject/openMINDS_core/blob/v4/instances/data/contentTypes/hyland.brainwaresrc.jsonld ??

2022-02-03 14:04 UTC, lzehl commented on instances/data/contentTypes/mearec.jsonld
> +  "name": "application/vnd.mearec+hdf",
should also be changed in the `@id` I will do the respective update in the KG for the software tools

2022-02-03 14:04 UTC, lzehl commented on instances/data/contentTypes/neopickle.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.pickle",
same as https://github.com/HumanBrainProject/openMINDS_core/blob/v4/instances/data/contentTypes/pickle.jsonld ???

2022-02-03 14:04 UTC, lzehl commented on instances/data/contentTypes/neuroshareapi.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.neurosharetypes",
would "neuroshare" not be sufficient?

2022-02-03 14:04 UTC, lzehl commented on instances/data/contentTypes/neuroshareapi.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.neurosharetypes",
why changing this and adding it again as new file? I guess this is a mixup?

2022-02-03 14:04 UTC, lzehl commented on instances/data/contentTypes/neurosharetypes0.jsonld
> +    "@vocab": "https://openminds.ebrains.eu/vocab/"
see comment for vnd.neuroshareapi.jsonld

2022-02-03 14:04 UTC, lzehl commented on instances/data/contentTypes/openephys.jsonld
> +  "name": "application/vnd.openephys+numpy",
I don't think +numpy applies here (then only .npy as ext would make sense) @apdavison ?

2022-02-03 14:04 UTC, lzehl commented on instances/data/contentTypes/pickle.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.neo-pickle",
please do not change this file but rather create this as new and adapt the existing pickle if necessary

2022-02-03 14:20 UTC, JuliaSprenger commented on instances/data/contentTypes/alphaomega0.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.alphaomega0-eng",
I understood this as a new output format coming from the same vendor / recent versions of the same system. Did you already have a case like this?

2022-02-03 14:24 UTC, JuliaSprenger commented on instances/data/contentTypes/brainwaredam.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.brainwaredam",
Yes, I didn't know that would be listed under hyland. I remove it.

2022-02-03 14:25 UTC, JuliaSprenger commented on instances/data/contentTypes/biocam.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.biocam",
will rename it

2022-02-03 14:25 UTC, JuliaSprenger commented on instances/data/contentTypes/brainwaref32.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.brainwaref32",
Yes, I didn't know that would be listed under hyland. I remove it.

2022-02-03 14:25 UTC, JuliaSprenger commented on instances/data/contentTypes/brainwaresrc.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.brainwaresrc",
Yes, I didn't know that would be listed under hyland. I remove it.

2022-02-03 14:26 UTC, JuliaSprenger commented on instances/data/contentTypes/mearec.jsonld
> +  "name": "application/vnd.mearec+hdf",
will change the name here and also the filename.

2022-02-03 14:28 UTC, JuliaSprenger commented on instances/data/contentTypes/neopickle.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.pickle",
I think this is a subcategory of the general pickle as neo can not ingest any pickled content, but only content dumped by neo.

2022-02-03 14:31 UTC, JuliaSprenger commented on instances/data/contentTypes/neuroshareapi.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.neurosharetypes",
yes, there was a mixup of file content between these two. I will fix it.

2022-02-03 14:33 UTC, JuliaSprenger commented on instances/data/contentTypes/openephys.jsonld
> +  "name": "application/vnd.openephys+numpy",
It's a folder structure containing npy (and maybe other) files. I am not sure how this is in general handled for folder based organization of data where you have a specific structure which contains specific files formats.

2022-02-03 14:36 UTC, JuliaSprenger commented on instances/data/contentTypes/pickle.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.neo-pickle",
Yes, makes sense. I put the neo specific pickle description in a separate descriptor.

2022-02-07 10:05 UTC, apdavison requested changes
This is great, many thanks Julia.

2022-02-07 10:05 UTC, apdavison commented on instances/data/contentTypes/alphaomega0.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.alphaomega0-eng",
What is the "-eng" for?

In general, I suggest adding a ".vX" for versions, so this would be something like `application/vnd.alphaomega.v0`

2022-02-07 10:05 UTC, apdavison commented on instances/data/contentTypes/axon.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.axon",
duplicate of https://github.com/HumanBrainProject/openMINDS_core/blob/v3/instances/data/contentTypes/moleculardevices.axon.jsonld

2022-02-07 10:05 UTC, apdavison commented on instances/data/contentTypes/neo+pickle.jsonld
> +  "name": "application/vnd.neo+pickle",
I suggest making this `application/vnd.neuralensemble.neo+pickle`, since there are many pieces of software called "neo" out there.

2022-02-07 10:05 UTC, apdavison commented on instances/data/contentTypes/neurosharetypes.jsonld
> +  "name": "application/vnd.neurosharetypes",
Does Neuroshare have its own file format(s)? I thought it was just an API to read in some existing formats.

If it does have its own formats, I suggest this should be `application/vnd.neuroshare.types`, and also make `application/vnd.neuroshareapi`--> `application/vnd.neuroshare.api`

2022-02-07 10:05 UTC, apdavison commented on instances/data/contentTypes/numpy.jsonld
> +  "name": "application/vnd.numpy",
Since NumPy also has the npz format, I think this should be `application/vnd.numpy.array`

(and then npz would be something like `application/vnd.numpy.multiarray`)

2022-02-07 10:05 UTC, apdavison commented on instances/data/contentTypes/openephys.jsonld
> +  "name": "application/vnd.openephys+numpy",
You can't use numpy.load to read such folder structures directly, so I would drop the `+numpy` suffix

2022-02-07 10:05 UTC, apdavison commented on instances/data/contentTypes/phy.jsonld
> +  "name": "application/vnd.phy+numpy",
What is different in phy files compared to simple .npy?

2022-02-07 10:05 UTC, apdavison commented on instances/data/contentTypes/spike2-32.jsonld
> +    "CED spike2 files (32)"
could this be "(32 bit)"?

2024-05-06 12:31 UTC, UlrikeS91 commented
I'm closing this draft since it is replace by the new PR in the instance-repo

2024-05-06 12:31 UTC, closed without merging