Update Matlab script content types
openMetadataInitiative/openMINDS_core pull request #307
Opened 2022-02-21 16:40 UTC by lzehl

should be:
+ plain script for `.m` extensions (is this really `text/x-matlab`?)
+ live script for `.mlx` extensions

2022-02-21 16:48 UTC, lzehl commented
@jagru20 & @apdavison whoever has more time :smile: 

I was really not sure how to define this format. Feel free to make counter suggestions.

2022-02-24 09:28 UTC, jagru20 commented
>     * plain script for `.m` extensions (is this really `text/x-matlab`?)

this is the MIME type, that the apache tika toolkit uses. I think this is ok.

2022-02-24 09:30 UTC, lzehl commented
@jagru20 I see. The mlx definition is okay though?

2022-02-24 09:39 UTC, jagru20 requested changes
As [this ](https://de.mathworks.com/help/matlab/matlab_prog/live-script-file-format.html)page states that .mlx files use .zip standards, I suggest naming the contenttype application/vnd.mathworks.live-script+zip

2022-02-24 09:39 UTC, jagru20 commented on instances/data/contentTypes/x-matlab.jsonld
> +		"MATLAB Plain Script"
👍

2022-02-24 09:39 UTC, jagru20 commented on instances/data/contentTypes/vnd.mathworks.live-script.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.mathworks.live-script",
As [this ](https://de.mathworks.com/help/matlab/matlab_prog/live-script-file-format.html)page states that .mlx files use .zip standards, I suggest naming the contenttype application/vnd.mathworks.live-script+zip

2022-02-24 09:39 UTC, jagru20 commented on instances/data/contentTypes/vnd.mathworks.live-script.jsonld
> +  "name": "application/vnd.mathworks.live-script",
As [this ](https://de.mathworks.com/help/matlab/matlab_prog/live-script-file-format.html)page states that .mlx files use .zip standards, I suggest naming the contenttype application/vnd.mathworks.live-script+zip

2022-02-24 09:46 UTC, lzehl commented on instances/data/contentTypes/vnd.mathworks.live-script.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.mathworks.live-script",
corrected

2022-02-24 09:46 UTC, lzehl commented on instances/data/contentTypes/vnd.mathworks.live-script.jsonld
> +  "name": "application/vnd.mathworks.live-script",
corrected

2022-02-24 09:46 UTC, lzehl commented
@jagru20 added also the link you provided as specification

2022-02-24 09:49 UTC, jagru20 approved these changes

2022-02-24 09:49 UTC, merged