Add ilastik content types
openMetadataInitiative/openMINDS_core pull request #309
Opened 2022-02-25 09:38 UTC by MaaikevS

@lzehl @UlrikeS91 

I added the content types for Ilastik based on Issue #296 
If you find that anything is missing or incorrect, let me know.

2022-02-25 10:09 UTC, UlrikeS91 commented
> @lzehl @UlrikeS91
> 
> I added the content types for Ilastik based on Issue #296 If you find that anything is missing or incorrect, let me know.

I'm not an expert. So, I won't involve myself. I added @jagru20, @apdavison and @lzehl as reviewers. I don't believe that all are required, but this way whoever has time first, can review the PR.

2022-03-18 10:06 UTC, jagru20 commented on instances/data/contentTypes/ilastik+csv.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.ilastik+csv",
according to the naming convention proposed by @apdavison the +suffix should be used for container formats. As far as I understand container formats, they are formats, that contain several other formats (like .zip files) therefore I assume +csv to be not correct and would just cut it off. But I am not 100% sure, @apdavison could you please give your thought on this?

2022-03-18 10:06 UTC, jagru20 commented on instances/data/contentTypes/ilastik+csv.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.ilastik+csv",
I think this would then also apply to others in this PR, as +tiff, +png etc.

2022-03-18 10:28 UTC, jagru20 commented on instances/data/contentTypes/ilastik+csv.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.ilastik+csv",
After one more thought about it, I would suggest naming it as subtypes like `application/vnd.ilastik.csv`

2022-04-05 12:13 UTC, jagru20 requested changes
If we can identify the purpose of the .csv and .ilp files, we should append them as the last subtype. I think the rest is ok.

2022-04-05 12:13 UTC, jagru20 commented on instances/data/contentTypes/ilastik+hdf5.jsonld
> +	"@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.ilastik+hdf5",
based on [this comment ](https://github.com/HumanBrainProject/openMINDS_core/pull/320#issuecomment-1073669832) it should be `/vnd.ilastik.purpose1+hdf5` if we can distinguish the purpose the files with .ilp extensions are for.

2022-04-05 12:13 UTC, jagru20 commented on instances/data/contentTypes/ilastik+csv.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.ilastik+csv",
based on [this comment ](https://github.com/HumanBrainProject/openMINDS_core/pull/320#issuecomment-1073669832) it should be `/vnd.ilastik.purpose1+csv` if we can distinguish the purpose the ilastik files with .csv extensions are for.

2022-04-13 11:41 UTC, lzehl commented
@k-dominik could you help us figuring out the open issues in the PR? For your information: openMINDS content types are inspired by IANA.org media types to define software (version) specific file types that can go beyond generic formats (e.g. a software specific json). We are trying to register all input and output content types of Ilastik in this PR.

2022-06-23 12:12 UTC, k-dominik reviewed
Hello all involved (@MaaikevS, @UlrikeS91, @jagru20, and @lzehl).

first of all I think it is a really cool effort to systematically attach some meaning to certain outputs of software.

as for the two different _purposes_ for csv/hdf5 one could probably use a term like _feature table_ or _result table_ or something like it.

Maybe as background: ilastik encapsulates different workflows, e.g. Pixel Classification that produces semantic segmentation (with output being either "simple segmentation" or "probabilities"), or Object Classification that does instance segmentation, produces output images like "Object Predictions", "Object Probabilites", "Object Identities", as well as the tables in csv/hdf5 format.

Do you maybe think it makes sense to add the workflow to the schema? E.g. `...image/vnd.ilastik.<workflowname>.probabilties+hdf5` ?

nitbit: usually ilastik is never capitalized, but it seems to be in the synonym field.

2022-09-29 10:03 UTC, lzehl commented
@k-dominik thank you so much for the clarifications.  I have a question in order to answer your question:
Are the internal file structure of the hdf5 files workflow specific? 

If yes, I would indeed split the content types up and follow the naming convention you suggested (`...image/vnd.ilastik.<workflowname>.probabilties+hdf5`). If no, I would keep the workflow out of the content type definition (`...image/vnd.ilastik.probabilties+hdf5`). 

I also have another favor to ask: could you give us a short (1-2 sentence) description we could add for each ilastik content type?
- `...image/vnd.ilastik.probabilties+hdf5`
- `...image/vnd.ilastik.probabilties+csv`
- `...image/vnd.ilastik.prediction+hdf5`
- `...image/vnd.ilastik.prediction+jpeg`
- `...image/vnd.ilastik.prediction+png`
- `...image/vnd.ilastik.prediction+tiff-stack`
- `...image/vnd.ilastik.prediction+tiff`
- `...image/vnd.ilastik.segmentations+hdf5`
- `...image/vnd.ilastik.segmentations+jpeg`
- `...image/vnd.ilastik.segmentations+png`
- `...image/vnd.ilastik.segmentations+tiff-stack`
- `...image/vnd.ilastik.segmentations+tiff`

2022-10-11 10:47 UTC, k-dominik commented
Okay I see - I don't think adding the workflow to the predictions type is necessary - while there could be a _semantic_ difference depending on the workflow, it will in any case be an nd-image.

For the 1-2 sentence description - can I assume that describing _probabilities_/_predictions_ (terms we use interchangeably) and _segmentation_ would be enough?

2022-10-11 11:34 UTC, lzehl commented
@k-dominik you mean we can only use "prediction" or only use "probabilties" in the content types above? I though the ...image/vnd.ilastik.probabilties+hdf5 and ...image/vnd.ilastik.prediction+hdf5 is not the same, or is it? Maybe we can have a short call to clarify this issue ?

2022-10-12 08:26 UTC, lzehl commented
RESULT discussion with @k-dominik :
    ...image/vnd.ilastik.hdf5
+ Reduce to one, because the internal structure does not change.

    ...application/vnd.ilastik.hdf5
+ contains feature table / object classification

    ...application/vnd.ilastik.csv
+ contains feature table

2022-10-12 08:29 UTC, lzehl commented
For the workflow project files:

...application/vnd.ilastik.project.WORKFLOW+hdf5

2022-10-12 08:32 UTC, k-dominik commented
we could start with the workflows

* `Pixel Classification`, and
* `Object Classification`.

2022-10-12 09:44 UTC, lzehl commented
SUMMARY with feedback from @apdavison & @k-dominik  : 

+ `image/vnd.ilastik.hdf5` (input/output)
+ `application/vnd.ilastik.features+hdf5` (output)
+ `application/vnd.ilastik.features+csv` (output)
+ `application/vnd.ilastik.pixelclassification+hdf5` (input/output)
+ `application/vnd.ilastik.objectclassification+hdf5` (input/output)

Note: additional input / output for ilastik are the general formats for png, jpeg, tiff, and tiff-stack (because they are not specially formatted/modified by ilastik in any way).

2022-10-18 12:45 UTC, lzehl commented
@MaaikevS sorry I forgot to ask: do you want to do the changes for this PR or should I take over?

2023-08-31 07:20 UTC, lzehl commented
@MaaikevS I think I'm not able to take make the needed edits on your branch. Could you do the final changes or should I close this PR and make a new one?

Here a summary of what needs to be done:

Please reduce the PR to the following content types
    image/vnd.ilastik.hdf5 (input/output)
    application/vnd.ilastik.features+hdf5 (output)
    application/vnd.ilastik.features+csv (output)
    application/vnd.ilastik.pixelclassification+hdf5 (input/output)
    application/vnd.ilastik.objectclassification+hdf5 (input/output)

Please adapt the atIDs of the content types to this (new) convention:
`"@id": "https://openminds.ebrains.eu/instances/contentTypes/image_vnd.ilastik.hdf5"`
`"@id": "https://openminds.ebrains.eu/instances/contentTypes/application_vnd.ilastik.features+hdf5"`
`"@id": "https://openminds.ebrains.eu/instances/contentTypes/application_vnd.ilastik.features+csv"`
`"@id": "https://openminds.ebrains.eu/instances/contentTypes/application_vnd.ilastik.pixelclassification+hdf5"`
`"@id": "https://openminds.ebrains.eu/instances/contentTypes/application_vnd.ilastik.objectclassification+hdf5"`

Please also adapt the file names to this (new) convention:
    image_vnd.ilastik.hdf5.jsonld
    application_vnd.ilastik.features+hdf5.jsonld
    application_vnd.ilastik.features+csv.jsonld
    application_vnd.ilastik.pixelclassification+hdf5.jsonld
    application_vnd.ilastik.objectclassification+hdf5.jsonld

2023-09-01 10:37 UTC, lzehl commented
@MaaikevS I'm closing your PR without merging due to the last discussions on this topic and the work connected to this. Thanks a lot for pushing this in the past.

2023-09-01 10:37 UTC, closed without merging