Creating the ExperimentalActivity
openMetadataInitiative/openMINDS_core pull request #323
Opened 2022-03-24 00:23 UTC by Peyman-N

Reflecting problems raised in #322

2022-03-25 14:05 UTC, lzehl requested changes

2022-03-25 14:05 UTC, lzehl commented on schemas/research/activity.schema.tpl.json
>  {
changing this schema is discussed in a separate issue https://github.com/HumanBrainProject/openMINDS_core/issues/322 and is incomplete in regard of the latest points made in this issue. If you want to put the change into this PR all of the decisions from that issue need to go into this PR.

2022-03-25 14:05 UTC, lzehl commented on schemas/research/experimentalActivity.schema.tpl.json
> +      "_instruction": "Add the dataset version in which this protocol execution was conducted.",
change to "Add the dataset version in which this experimental activity was conducted."

2022-03-25 14:05 UTC, lzehl commented on schemas/research/experimentalActivity.schema.tpl.json
> +      "_instruction": "Add the initial preparation type for this protocol execution.",
change to "Add the initial preparation type for this experimental activity."

2022-03-25 14:05 UTC, lzehl commented on schemas/research/experimentalActivity.schema.tpl.json
> +      "_instruction": "Add all protocols that were used in this protocol execution.",
change to "Add all protocols that were used in this experimental activity."

2022-03-25 14:05 UTC, lzehl commented on schemas/research/activity.schema.tpl.json
>    "required": [
If I recall correctly required property list is merged for extensions. Input/output are already required in Activity.

2022-03-25 14:05 UTC, lzehl commented on schemas/research/protocolExecution.schema.tpl.json
>    "_type": "https://openminds.ebrains.eu/core/ProtocolExecution",
I actually would not change this Schema extension. With inheriting directly from Activity the ProtocolExecution stays independent of the concept Schema ExperimentalActivity which is the template for in-depth Activity Schemas. We will gain more flexibility that way for in-depth needs. We can still apply the extension inheritance at a later point if we see we did not need that flexibility.

2022-03-25 15:22 UTC, UlrikeS91 commented on schemas/research/activity.schema.tpl.json
>    "required": [
This is the activity schema you are commenting on 😉 So, this needs to remain as is ☺️

2022-03-25 15:26 UTC, UlrikeS91 commented on schemas/research/protocolExecution.schema.tpl.json
>    "_type": "https://openminds.ebrains.eu/core/ProtocolExecution",
YEah, sounds like a good idea and won't hurt in the long run. Except now @Peyman-N has to add all the properties again that were kick out because of this change 😛

2022-03-28 07:09 UTC, lzehl commented on schemas/research/activity.schema.tpl.json
>    "required": [
ah yes... thanks for the correction.

2022-03-31 13:56 UTC, lzehl commented
@Peyman-N to summarize the additional TODOs from issue #322 for this PR directly here:

+ rename the Activity property "parameter set" to "custom property set" 
+ rename the schema ParameterSet to CustomPropertySet
+ rename the schema NumericalParameter to NumericalProperty
+ rename the schema StringParameter to StringProperty
+ extending / revising the CustomPropertySet schema (see also below)
+ adding a Configuration schema (see also below)
+ adding a PropertyValueList schema (see also below)

**Revision of CustomPropertySet schema:**
```json
{
  "_type": "https://openminds.ebrains.eu/core/CustomPropertySet",
  "required": [
    "context",
    "relevantFor",
    "definedIn"
  ],
  "properties": {
    "context": {
      "type": "string",
      "_instruction": "Enter the common context for this custom property set."
    },
    "relevantFor": {
      "_instruction": "Add the technique for which this custom property set is relevant.",
      "_linkedTypes": [
        "https://openminds.ebrains.eu/controlledTerms/Technique"
      ]
    },
    "definedIn": {
      "_instruction": "Add a file or configuration that specifies the custom property set of the given context.",
      "_linkedTypes": [
        "https://openminds.ebrains.eu/core/File",
        "https://openminds.ebrains.eu/core/Configuration",
        "https://openminds.ebrains.eu/core/PropertyValueList"
      ]
    }
  }
}
```

**Suggested Configuration schema:**
```json
{
  "_type": "https://openminds.ebrains.eu/core/Configuration",
  "required": [
    "configuration",
    "definitionFormat"
  ],
  "properties": {
    "lookupLabel": {
      "type": "string",
      "_instruction": "Enter a lookup label for this configuration that may help you to more easily find it again."
    },
    "configuration": {
      "type": "string",
      "_instruction": "Enter the configuration in a simple text based format (e.g., JSON, or YAML)."
    },
    "definitionFormat": {
      "_instruction": "Add the content type of the defined configuration.",
      "_linkedTypes": [
        "https://openminds.ebrains.eu/core/ContentType"
      ]
    }
  }
}
```

**Suggested changes for PropertyValueList schema:**
```json
{
  "_type": "https://openminds.ebrains.eu/core/PropertyValueList",
  "required": [
    "propertyValuePair"
  ],
  "properties": {
    "lookupLabel": {
      "type": "string",
      "_instruction": "Enter a lookup label for this key-value list that may help you to more easily find it again."
    },
    "propertyValuePair": {
      "type": "array",
      "minItems": 1,
      "uniqueItems": true,
      "_instruction": "Add all numerical and string property-value pairs that belong to this list.",
      "_embeddedTypes": [
        "https://openminds.ebrains.eu/core/NumericalProperty",
        "https://openminds.ebrains.eu/core/StringProperty"
      ]
    }
  }
}
```
Hope this helps to push this PR

2022-04-26 13:11 UTC, Peyman-N commented
- [ ] rename the Activity property "parameter set" to "custom property set"
- [ ] rename the schema ParameterSet to CustomPropertySet
- [ ] rename the schema NumericalParameter to NumericalProperty
- [ ] rename the schema StringParameter to StringProperty
- [ ] extending / revising the CustomPropertySet schema (see also below)
- [ ] adding a Configuration schema (see also below)
- [ ] adding a PropertyValueList schema (see also below)

2022-04-26 13:21 UTC, Peyman-N commented
@lzehl I just checked, it seems that I have applied all the requested modifications asked by you in your [comment](https://github.com/HumanBrainProject/openMINDS_core/pull/323#issuecomment-1084624140). Can you please review it again and let me know, what are the resting issues for this PR?

2022-05-25 15:25 UTC, apdavison approved these changes

2022-06-15 10:26 UTC, lzehl requested changes
@Peyman-N nearly ready to be merged two small things: 
+ all JSONs should end with a new line (according to POSIX standard)
+ small correction in one of the descriptions (see comment) to be consistent with the terms

2022-06-15 10:26 UTC, lzehl commented on schemas/research/propertyValueList.schema.tpl.json
> +            "_instruction": "Enter a lookup label for this key-value list that may help you to more easily find it again."
let's stick to "property-value" (instead of "key-value"; you can put it in brackets "property-value (also called key-value)")

2022-06-21 07:50 UTC, lzehl approved these changes

2022-06-21 07:51 UTC, merged

2022-06-21 07:52 UTC, lzehl commented
@olinux this will require a bit of clean up within the KG