Create FileArchive schema and ContentTypes for the EBRAINS image service
openMetadataInitiative/openMINDS_core pull request #325
Opened 2022-03-28 17:15 UTC by lzehl

We introduce the FileArchive schema to point to specifically structured file location containing typically a large number of files, that should not be indexed by a graph database.

Use case within EBRAINS: image service buckets / containers for Neuroglancer or DCI (respective content types are attached to the PR; @apdavison & @jagru20 please help with the review)

2022-03-28 17:55 UTC, lzehl commented
@olinux we need to have some clarification for the image-service bucket with the DZI files. the rest is ready to be reviewed.

2022-03-29 12:14 UTC, olinux approved these changes

2022-03-29 13:20 UTC, jagru20 requested changes
I am a bit limited in knowledge about these repository types, thus I am not able to evaluate if the names are chosen appropriately but from the description provided it seems plausible. 
Found some minor cosmetic issues.

2022-03-29 13:20 UTC, jagru20 commented on instances/data/contentTypes/vnd.ebrains.image-service.microsoft-deep-zoom.jsonld
> +  "description": "This content type defines a file repository produced by the EBRAINS image-service holding image files that are directly ingestable by Microsoft Deep Zoom.",
indentation

2022-03-29 13:20 UTC, jagru20 commented on instances/data/contentTypes/vnd.ebrains.image-service.neuroglancer.jsonld
> +  "description": "This content type defines a file repository produced by the EBRAINS image-service holding image files that are directly ingestable by Neuroglancer.",
indentation

2022-03-29 13:20 UTC, jagru20 commented on instances/data/contentTypes/vnd.ebrains.image-service.microsoft-deep-zoom.jsonld
> +	"synonym": null
I think if they are null, they can be omitted as they are not required.

2022-03-29 13:20 UTC, jagru20 commented on instances/data/contentTypes/vnd.ebrains.image-service.neuroglancer.jsonld
> +	"synonym": null
I think if they are null, they can be omitted as they are not required.

2022-03-30 06:32 UTC, lzehl commented on instances/data/contentTypes/vnd.ebrains.image-service.microsoft-deep-zoom.jsonld
> +	"synonym": null
this is true, I usually leave them in though for the controlled terms, content types and licenses because we should fill them at one point (as a reminder for us)

2022-03-30 06:32 UTC, lzehl commented on instances/data/contentTypes/vnd.ebrains.image-service.neuroglancer.jsonld
> +	"synonym": null
this is true, I usually leave them in though for the controlled terms, content types and licenses because we should fill them at one point (as a reminder for us)

2022-03-30 06:33 UTC, lzehl commented on instances/data/contentTypes/vnd.ebrains.image-service.microsoft-deep-zoom.jsonld
> +  "description": "This content type defines a file repository produced by the EBRAINS image-service holding image files that are directly ingestable by Microsoft Deep Zoom.",
corrected

2022-03-30 06:37 UTC, lzehl commented on instances/data/contentTypes/vnd.ebrains.image-service.neuroglancer.jsonld
> +	"synonym": null
I've deleted "relatedMediaType" (which we will not have for this case) and added a synonym

2022-03-30 06:38 UTC, lzehl commented on instances/data/contentTypes/vnd.ebrains.image-service.neuroglancer.jsonld
> +  "description": "This content type defines a file repository produced by the EBRAINS image-service holding image files that are directly ingestable by Neuroglancer.",
done

2022-03-30 06:38 UTC, lzehl commented on instances/data/contentTypes/vnd.ebrains.image-service.microsoft-deep-zoom.jsonld
> +	"synonym": null
I've deleted "relatedMediaType" (which we will not have for this case) and added a synonym

2022-03-30 06:53 UTC, lzehl commented
@jagru20 I'm not yet happy about the content types. I will most likely change them if I get the feedback I need.

2022-03-30 07:14 UTC, lzehl commented
@olinux @jagru20 @apdavison I've added the content types of Microsoft Deep Zoom software also to this PR since they were missing in our list.

2022-03-30 08:44 UTC, lzehl commented
@jagru20 @olinux @apdavison: 
**The PR is ready to be reviewed again.** With the help of @xgui3783 I've updated the content types for the image service and, for completion and references, added the individual content types of the related software (deep zoom and neuroglancer).

@marcnm @alexisdurieux In the long run would be good if you could online document the specifications for each of the image-service bucket/container types so that we can add a specification link to the respective content types.

2022-03-30 09:42 UTC, jagru20 approved these changes

2022-03-31 07:09 UTC, merged