Create meshview+json.jsonld
openMetadataInitiative/openMINDS_core pull request #332
Opened 2022-06-07 05:52 UTC by MaaikevS

Related to #293 
There might be more content types that need to be added, but I need this one for a dataset

2022-06-07 12:15 UTC, MaaikevS commented
@lzehl Would you be able to review this?

2022-06-15 10:58 UTC, lzehl requested changes
if changes are actually needed depends on the answer to my question ( see comment).
Formally the jsonld looks fine.

2022-06-15 10:58 UTC, lzehl commented on instances/data/contentTypes/meshview+json.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.meshview+json",
what is it used for? what does it contain? maybe we can make the name a bit more specific (e.g. vnd.meshview.config+json)

2022-06-15 11:00 UTC, lzehl commented on instances/data/contentTypes/meshview+json.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.meshview+json",
if possible provide a small description (property "description") or add a link to the specification of this format (property "specification"

2022-06-15 11:01 UTC, MaaikevS commented on instances/data/contentTypes/meshview+json.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.meshview+json",
Thanks for looking at this. The json file is the file that is uploaded to the meshview viewer, so it is for the visualisation of point coordinates. So would you want it to become vnd.meshview.visualization+json? Or something like this?

2022-06-15 11:07 UTC, lzehl commented on instances/data/contentTypes/meshview+json.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.meshview+json",
Mh if this is an input file then I think it should be a contentType of the software that produced it (except you have to write it manually). So not MeshView but?

2022-06-15 11:13 UTC, MaaikevS commented on instances/data/contentTypes/meshview+json.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.meshview+json",
Hmm I don't know how it was produced initially, I will check. It has the nested structure and properties that are compatible with meshview

2022-06-15 11:28 UTC, Majpuc commented on instances/data/contentTypes/meshview+json.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.meshview+json",
Hi, MeshView (e.g. https://meshview.apps.hbp.eu/?atlas=ABA_Mouse_CCFv3_2017_25um) has two types of input. 1. a json file created by Nutil. 2. The user is providing a coordinate list of points x,y,z by pasting them directly in the window under "clouds from coordinates" I hope this helps :)

2022-06-15 11:32 UTC, MaaikevS commented on instances/data/contentTypes/meshview+json.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.meshview+json",
Thanks @Majpuc. Can you please advise us then on what the correct content types should be regarding Issues #294 and #293 
It would be great to finish those content types that they can actually be used in the curation!

2022-06-15 11:40 UTC, Majpuc commented on instances/data/contentTypes/meshview+json.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.meshview+json",
I have asked the developer. Will come back to you asap

2022-06-15 11:41 UTC, lzehl commented on instances/data/contentTypes/meshview+json.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.meshview+json",
@Majpuc I'm missing the JSON from the list we discussed for Nutil (cf. #294); could you clarify/verify that we need a JSON for Nutil? What is the content / structure of this file?

The second input seems to be somewhat MeshView specific; but the list is of what format? TXT, CSV, ? and what is the order of the list ( is it: [[x1, y1, z1],[x2, y2, z2], ...] OR [[x1, x2, ...], [y1, y2, ...], [z1, z2, ...]])?

2022-06-15 11:45 UTC, MaaikevS commented on instances/data/contentTypes/meshview+json.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.meshview+json",
The JSON coordinates are stored [[x1, y1, z1],[x2, y2, z2], ...]
The "clouds from coordinates" is CSV or TSV but copy-pasted into the box

2022-06-15 11:49 UTC, Majpuc commented on instances/data/contentTypes/meshview+json.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.meshview+json",
All the content types were defined in our common spreadsheet https://docs.google.com/spreadsheets/d/1e3-D-uCsMeYCSkjBmPC--jpOH1iJZWqcj58Mb6GB0T4/edit#gid=0
the json is a Nutil Quantifier output file.
The cloud from coordinate are listed [x1, y1, z1],[x2, y2, z2], ...

2022-06-15 12:20 UTC, Majpuc commented on instances/data/contentTypes/meshview+json.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.meshview+json",
Concerning NutilQuantifier output jsons:  the coordinate files are identical across the board, from Nutil v0.33 to v0.8.0

2022-06-15 12:36 UTC, MaaikevS commented on instances/data/contentTypes/meshview+json.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.meshview+json",
Actually, the coordinates are listed as one long list of x,y,z coordinates that are not stored as individual lists. My earlier response was incorrect. They are stored as [x1, y1, z1, x2, y2, z2,..., xn, yn, zn]. So they are extracted by meshview as triplets.

2022-06-15 13:21 UTC, lzehl commented on instances/data/contentTypes/meshview+json.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.meshview+json",
this turns out to be very complicated :sweat_smile: 

I've got a bit lost now. Let's summarize:

MeshView has two different input Formats (A, B)
A: .json extension; should be the ContentType of Nutil Quantifier JSON
B: .tsv or .csv (as manual copy/paste); required structure  [x1, y1, z1, x2, y2, z2,..., xn, yn, zn] ??? (which would only be one line and no tab separation?); Could be considered as a MeshView specific input file.

2022-06-15 13:28 UTC, MaaikevS commented on instances/data/contentTypes/meshview+json.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.meshview+json",
Sorry to make it more difficult. Let me explain what I know about the json files.
The coordinates in the json file are stored as follows: there is a list of values for "triplets". The values represent the x,y,z coordinates and are ordered like this:[x1, y1, z1, x2, y2, z2,..., xn, yn, zn] 
![image](https://user-images.githubusercontent.com/31585951/173838279-d41a7591-4711-4e60-af28-1ec3f0234d41.png)

If you want to use the other option and copy paste the coordinates directly into meshview you just copy a list of values that are comma or tab separated, i.e. x1, y1, z1, x2, y2, z2,..., xn, yn, zn

Hope this helps.

2022-06-15 14:16 UTC, lzehl commented on instances/data/contentTypes/meshview+json.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.meshview+json",
okay. I slowly start to get a picture. I would say the following:

The JSON has to be captured as Nutil Quantifier content type. This Nutil Quantifier content type can then be an input format for the MeshViewer Software (version x).

The other input should be defined as MeshView content type. Here it needs to be clarified what the valid structures are to be directly copy/past. It might be that we need to define one MeshView content type for CSV, for TSV and potentiall TXT. @apdavison what do you think?

2022-06-15 14:24 UTC, MaaikevS commented on instances/data/contentTypes/meshview+json.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.meshview+json",
Ok, if we can cover the json with the Nutil content type, then it is fine with me. We may want to clean up those issues then, since it is very confusing as it is.

Regarding the second option for csv,tsv etc. I would not make a content type for this as you would not really use it as such, since the file itself cannot be uploaded to Meshview. 
I have extracted the x,y,z coordinates of the json file and stored them in a csv format, but the content type is just csv. The whole point it that that csv file is an open format and not linked to meshview

2022-06-15 14:55 UTC, lzehl commented on instances/data/contentTypes/meshview+json.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.meshview+json",
I agree with cleaning up the issues. @Majpuc could you help here?

For the MeshView: this is not just a csv because it assumes a certain structure of the content. Nonetheless I need to discuss if copy/paste input qualifies as being registered as ContentTypes (@apdavison & @jagru20 your feedback is needed for this).

For now and for your purpose the Nutil Content Type is more important I guess?

2022-06-22 17:55 UTC, MaaikevS commented on instances/data/contentTypes/meshview+json.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.meshview+json",
@lzehl I now changed meshview to nutil quantifier. Hope this is ok for now.
Could you have a look and merge if you are happy with it like this? 
Many thanks!

2022-06-23 07:19 UTC, lzehl approved these changes

2022-06-23 07:20 UTC, merged

2022-06-23 07:22 UTC, MaaikevS commented
Thanks @lzehl