add voluba v1 linear transform content type
openMetadataInitiative/openMINDS_core pull request #351
Opened 2022-09-13 09:02 UTC by xgui3783

addresses https://github.com/HumanBrainProject/openMINDS_core/issues/350

cc @fsdavid @JThoennissen If you guys could raise any issue, if you can find any?

ping @lzehl Can you please review?

2022-09-14 07:56 UTC, lzehl requested changes
@xgui3783 thank you for preparing this PR :slightly_smiling_face:  There is one issue that @apdavison should confirm/comment on and one smaller issue for the specification.

2022-09-14 07:56 UTC, lzehl commented on instances/data/contentTypes/voluba-v1-linearTransform.jsonld
> +	"relatedMediaType": "https://www.iana.org/assignments/media-types/application/json",
this should only be filled if it is an exact match, correct @apdavison (or did we now do it also for just "relations"?)

2022-09-14 07:56 UTC, lzehl commented on instances/data/contentTypes/voluba-v1-linearTransform.jsonld
> +    "specification": "https://raw.githubusercontent.com/FZJ-INM1-BDA/voluba/fa8e58dbe91a577dd0e6f6a8bf82c06b7e3e72e3/.openminds/voluba.v1.linearTransform.json"
this is not the specification :sweat_smile: that's just our content type registration. Leave it empty if you do not yet have a documentation on how this JSON looks like (required key-value pairs, expected values, etc.).

If you want to deliver at least a bit of documentation here use the "description" property to write a small (free text) paragraph directly in the content type instance.

2022-12-01 10:19 UTC, xgui3783 commented
ping @lzehl, I have fixed your suggests.

2022-12-01 10:30 UTC, lzehl commented
@xgui3783 I've updated the indentation to 2 spaces per tab (recent guideline for openMINDS) and updated the synonym a bit. If you are happy with it I can merge it.

2022-12-01 10:38 UTC, xgui3783 commented
@lzehl I am happy! Thanks for your help.

2022-12-01 14:32 UTC, lzehl approved these changes

2022-12-01 14:32 UTC, merged