Clean up: research product version
openMetadataInitiative/openMINDS_core pull request #387
Opened 2023-02-10 11:25 UTC by UlrikeS91

MINOR changes:
- improved instructions
- establish alphabetical order
- establish correct order within the properties

MAJOR changes:
none

SPECIAL ATTENTION:
- removed maxLength for both description & shortName because I don't believe that we adhered to this so far and I don't see a good reason to have it here anymore
- removed the notion that no references are allow from the instructions of the description

2023-02-10 17:16 UTC, lzehl requested changes

2023-02-10 17:16 UTC, lzehl commented on schemas/products/researchProductVersion.schema.tpl.json
> +      "maxItems": 5,
please remove this as well. if remove other restrictions we should not introduce one here. Each system (e.g. EBRAINS KG can decide this for themselves)

2023-02-10 17:16 UTC, lzehl commented on schemas/products/researchProductVersion.schema.tpl.json
> +      "maxItems": 5,
adapt then again the instructions as well

2023-02-13 10:13 UTC, UlrikeS91 commented on schemas/products/researchProductVersion.schema.tpl.json
> +      "maxItems": 5,
Agreed and updated 🙂

2023-02-20 10:54 UTC, lzehl requested changes

2023-02-20 10:54 UTC, lzehl commented on schemas/products/researchProductVersion.schema.tpl.json
> +      "_instruction": "Add all further publications besides the full documentation that provide the original context for the production of this research product version (e.g., an original research ar
I do not understand the addition. And "supplementary material" would include also learning resources which is explicitly not what is meant here.

2023-02-28 12:37 UTC, aeidi89 commented on schemas/products/researchProductVersion.schema.tpl.json
> +      "_instruction": "Enter the date (actual or intended) on which this research product version was first release, formatted as '2023-02-07'."
Suggest changing '2023-02-07' to 'YYYY-MM-DD'

2023-02-28 13:33 UTC, lzehl approved these changes
@aeidi89 I've updated the schema with your issue and adapted the instructions a bit of the "relatedPublication" property. Please double check and feel free to merge if you approve the changes.

2023-03-06 11:27 UTC, Peyman-N approved these changes

2023-03-08 18:33 UTC, merged