Clean up: specimen state
openMetadataInitiative/openMINDS_core pull request #390
Opened 2023-02-10 11:41 UTC by UlrikeS91

MINOR changes:
- improved instructions

MAJOR changes:
none

SPECIAL ATTENTION:
none

2023-02-14 13:26 UTC, lzehl requested changes

2023-02-14 13:26 UTC, lzehl commented on schemas/research/specimenState.schema.tpl.json
>    "properties": {
@UlrikeS91 this has nothing to do with the cleanup but it came up during a curation in EBRAINS now. We will also need an internalIdentifier for specimenStates (optional). Could you add it?

2023-02-17 10:14 UTC, UlrikeS91 commented on schemas/research/specimenState.schema.tpl.json
>    "properties": {
done

2023-02-22 09:44 UTC, lzehl approved these changes

2023-02-22 09:44 UTC, merged