Clean up: affiliation
openMetadataInitiative/openMINDS_core pull request #391
Opened 2023-02-10 11:48 UTC by UlrikeS91

MINOR changes:
- improved instructions
- establish alphabetical order

MAJOR changes:
none

SPECIAL ATTENTION:
none

2023-02-14 13:29 UTC, lzehl requested changes

2023-02-14 13:29 UTC, lzehl commented on schemas/actors/affiliation.schema.tpl.json
> +      "_instruction": "Add the organization or consortium another party is a member of.",
or was

2023-02-14 13:29 UTC, lzehl commented on schemas/actors/affiliation.schema.tpl.json
> +      "_instruction": "Add the organization or consortium another party is a member of.",
not sure if the "another party" is understood here. but I also do not have a better suggestion

2023-02-17 10:19 UTC, UlrikeS91 commented on schemas/actors/affiliation.schema.tpl.json
> +      "_instruction": "Add the organization or consortium another party is a member of.",
added the past tense; let's see if @apdavison has any suggestion for the party or if this is ok as is

2023-02-22 09:47 UTC, lzehl commented on schemas/actors/affiliation.schema.tpl.json
> +      "_instruction": "Add the organization or consortium another party is a member of.",
Suggestion (since we use party now consistently for all other occurrences I think my only issue here is that the relation from the affiliation to the party is a bit unclear): "Add the organization or consortium the party of this affiliation is a member of."

2023-02-22 09:48 UTC, lzehl commented on schemas/actors/affiliation.schema.tpl.json
> +      "_instruction": "Add the organization or consortium another party is a member of.",
OR: "Add the organization or consortium that according to this affiliation another party is a member of."

2023-02-28 10:59 UTC, lzehl approved these changes

2023-02-28 11:00 UTC, lzehl commented on schemas/actors/affiliation.schema.tpl.json
> +      "_instruction": "Add the organization or consortium another party is a member of.",
you can leave it as is as well. I don't have a strong opinion on this

2023-02-28 11:00 UTC, lzehl commented
@apdavison or @Peyman-N or @aeidi89 feel free to merge if you also approve

2023-02-28 11:38 UTC, aeidi89 commented on schemas/actors/affiliation.schema.tpl.json
> +      "_instruction": "Enter the end date of this affiliation, formatted as '2023-02-07'. Leave blank if this affiliation is still current."
Because of differences across European and American ways of writing the date I would suggest changing '2023-02-07' to 'yyyy-mm-dd'

2023-02-28 11:41 UTC, aeidi89 requested changes
Looks good.
With regards to the discussion regarding tense, I think line 15 is good as is.

2023-02-28 11:41 UTC, aeidi89 commented on schemas/actors/affiliation.schema.tpl.json
> +      "_instruction": "Enter the start date of this affiliation, formatted as '2023-02-07'."
See comment above, change to 'yyyy-mm-dd'

2023-02-28 11:41 UTC, aeidi89 commented on schemas/actors/affiliation.schema.tpl.json
> +      "_instruction": "Enter the end date of this affiliation, formatted as '2023-02-07'. Leave blank if this affiliation is still current."
Because of differences across European and American ways of writing the date I would suggest changing '2023-02-07' to 'yyyy-mm-dd'

2023-02-28 11:42 UTC, aeidi89 commented
@lzehl Would you mind checking this and merge?

2023-02-28 11:59 UTC, lzehl commented on schemas/actors/affiliation.schema.tpl.json
> +      "_instruction": "Enter the end date of this affiliation, formatted as '2023-02-07'. Leave blank if this affiliation is still current."
that is a good point. we should double check this for all instructions of entering dates or datetimes.

2023-02-28 12:00 UTC, lzehl approved these changes
@aeidi89 your suggestions are integrated please double check and merge when you are happy

2023-02-28 12:04 UTC, aeidi89 approved these changes
Looks good.

2023-02-28 12:04 UTC, merged