Clean up: content type
openMetadataInitiative/openMINDS_core pull request #397
Opened 2023-02-13 12:02 UTC by UlrikeS91

MINOR changes:
- improved instructions
- establish alphabetical order

MAJOR changes:
none

SPECIAL ATTENTION:
none

2023-02-14 18:24 UTC, lzehl requested changes

2023-02-14 18:24 UTC, lzehl commented on schemas/data/contentType.schema.tpl.json
> +      "_instruction": "Enter the name of this content type following a IANA-inspired convention."
IANA.org inspired convention

2023-02-17 10:22 UTC, UlrikeS91 commented on schemas/data/contentType.schema.tpl.json
> +      "_instruction": "Enter the name of this content type following a IANA-inspired convention."
done

2023-02-22 09:49 UTC, lzehl approved these changes

2023-02-22 09:49 UTC, merged