Clean up: content type pattern
openMetadataInitiative/openMINDS_core pull request #398
Opened 2023-02-13 12:05 UTC by UlrikeS91

MINOR changes:
- improved instructions

MAJOR changes:
none

SPECIAL ATTENTION:
none

2023-02-14 18:31 UTC, lzehl requested changes

2023-02-14 18:31 UTC, lzehl commented on schemas/data/contentTypePattern.schema.tpl.json
> +      "_instruction": "Add the content type that can be defined by the regular expression for this content type pattern (e.g., for file extensions).",
... of this content type pattern (e.g., for file extensions).

2023-02-14 18:31 UTC, lzehl commented on schemas/data/contentTypePattern.schema.tpl.json
> +      "_instruction": "Enter the regular expression for the file names and/or extensions that defines this content type pattern."
"Enter a regular expression for the common part of the names of files (including file path and extension) that are all formatted using the content type defined in this content type pattern." 

(feel free to optimize further)

2023-02-17 10:27 UTC, UlrikeS91 commented on schemas/data/contentTypePattern.schema.tpl.json
> +      "_instruction": "Add the content type that can be defined by the regular expression for this content type pattern (e.g., for file extensions).",
done

2023-02-17 10:28 UTC, UlrikeS91 commented on schemas/data/contentTypePattern.schema.tpl.json
> +      "_instruction": "Enter the regular expression for the file names and/or extensions that defines this content type pattern."
made another suggestion, let me know if that works

2023-02-22 09:50 UTC, lzehl approved these changes

2023-02-22 09:50 UTC, merged