Clean up: copyright
openMetadataInitiative/openMINDS_core pull request #400
Opened 2023-02-13 12:15 UTC by UlrikeS91

MINOR changes:
- improved instructions

MAJOR changes:
none

SPECIAL ATTENTION:
none

2023-02-15 07:59 UTC, lzehl requested changes

2023-02-15 07:59 UTC, lzehl commented on schemas/data/copyright.schema.tpl.json
> +      "_instruction": "Enter the year during which the copyright was first asserted follwoing the defined pattern (e.g., 2023)."
@apdavison this is something we need to overthink correct? in principle the copyright has to be renewed for each year which would make the link to this type an array and then this instruction should read something like this: "Enter the year during which the copyright was claimed following the defined pattern (e.g., 2023)."

@UlrikeS91 besides this issue there is a typo in "follwoing" :wink:

2023-02-17 10:29 UTC, UlrikeS91 commented on schemas/data/copyright.schema.tpl.json
> +      "_instruction": "Enter the year during which the copyright was first asserted follwoing the defined pattern (e.g., 2023)."
I'll wait for feedbakc form @apdavison before making any changes

2023-02-28 16:09 UTC, apdavison commented on schemas/data/copyright.schema.tpl.json
> +      "_instruction": "Enter the year during which the copyright was first asserted follwoing the defined pattern (e.g., 2023)."
yes, an array would be a nice solution. The instructions should then be something like "Enter the year during which the copyright was first asserted and, optionally, later years during which updated versions were published."

2023-02-28 16:11 UTC, lzehl commented on schemas/data/copyright.schema.tpl.json
> +      "_instruction": "Enter the year during which the copyright was first asserted follwoing the defined pattern (e.g., 2023)."
perfect. thanks for the feedback. I'll do the changes

2023-02-28 16:16 UTC, lzehl approved these changes
@apdavison I've updated the schema. Please double check and feel free to merge if you approve. Question: should the copyright on RPVs should also become an array? (in case the copyright holder changed for a published version?)

2023-03-06 10:28 UTC, Peyman-N approved these changes

2023-03-06 10:28 UTC, merged