Clean up: custom property set
openMetadataInitiative/openMINDS_core pull request #401
Opened 2023-02-13 12:25 UTC by UlrikeS91

MINOR changes:
- improved instructions
- establish alphabetical order
- renamed `definedIn` with `dataLocation`, which merges two existing properties which were used in approx. the same way; details of what data is found there or how the data is stored, should be stated in the instructions

MAJOR changes:
none

SPECIAL ATTENTION:
none

CHANGELOG:
- replaced link to technique for `relevantFor` with new category `technique` (which includes techniques, analysisTechniques and stimulationTechniques); see https://github.com/HumanBrainProject/openMINDS_controlledTerms/pull/393

2023-02-15 08:01 UTC, lzehl requested changes

2023-02-15 08:01 UTC, lzehl commented on schemas/research/customPropertySet.schema.tpl.json
> +    "dataLocation": {
or we call this "about" ?? I think the meaning would fit better. @apdavison @Peyman-N we need your feedback here

2023-02-17 10:35 UTC, UlrikeS91 commented on schemas/research/customPropertySet.schema.tpl.json
> +    "dataLocation": {
No, `about` will be wrong in this context. What we expect, is the location of the file (or other entities) that defines this set. We used `about` in schemas to define what the schema is about (e.g., a `learningResource` could be about a `dataset`). Here we are asking for the file (or other entity) that is about this set - not the other way around.

2023-02-22 09:52 UTC, lzehl commented on schemas/research/customPropertySet.schema.tpl.json
> +    "dataLocation": {
okay with me.

2023-02-22 09:53 UTC, lzehl approved these changes

2023-02-22 09:53 UTC, lzehl commented
@Peyman-N or @apdavison feel free to merge if you also approve

2023-02-24 14:27 UTC, Peyman-N approved these changes

2023-02-24 14:27 UTC, merged