Clean up: GRIDID
openMetadataInitiative/openMINDS_core pull request #412
Opened 2023-02-13 13:49 UTC by UlrikeS91

MINOR changes:
- improved instructions
- (re)moved schema from miscellaneous to new folder called digitalIdentifier for better grouping and decluttering of the miscellaneous folder

MAJOR changes:
none

SPECIAL ATTENTION:
none

2023-02-20 08:20 UTC, lzehl approved these changes

2023-02-20 08:21 UTC, lzehl commented
@apdavison or @Peyman-N feel free to merge if you are also happy with the changes

2023-02-23 13:34 UTC, Peyman-N approved these changes

2023-02-23 13:34 UTC, Peyman-N commented on schemas/digitalIdentifier/GRIDID.schema.tpl.json
> +      "_instruction": "Enter the identifier for research organizations provided by the International Digital Object Identifier Foundation ('Gloabl Research Identifier Database IDentifier'; GRIDID) as
Typo `Global`

2023-02-23 13:36 UTC, Peyman-N requested changes
Typo `Global`

2023-02-28 10:33 UTC, lzehl approved these changes
I've corrected the typo. 

@Peyman-N or @apdavison or @aeidi89 feel free to merge if you also approve now

2023-02-28 10:38 UTC, Peyman-N approved these changes

2023-02-28 10:38 UTC, merged

2023-02-28 10:38 UTC, aeidi89 approved these changes
Looks good.