Clean up: ORCID
openMetadataInitiative/openMINDS_core pull request #423
Opened 2023-02-13 14:37 UTC by UlrikeS91

MINOR changes:
- improved instructions
- (re)moved schema from miscellaneous to new folder called digitalIdentifier for better grouping and decluttering of the miscellaneous folder

MAJOR changes:
none

SPECIAL ATTENTION:
none

2023-02-20 08:41 UTC, lzehl requested changes

2023-02-20 08:41 UTC, lzehl commented on schemas/digitalIdentifier/ORCID.schema.tpl.json
> +      "_instruction": "Enter the identifier for researchers provided by the Open Researcher and Contributor ID, Inc. (ORCID) as an internationalized resource identifier (IRI) following the defined pa
... by Open Researcher and Contributor ID, Inc. (ORCID, Inc.)

2023-02-20 08:41 UTC, lzehl commented on schemas/digitalIdentifier/ORCID.schema.tpl.json
> +      "_instruction": "Enter the identifier for researchers provided by the Open Researcher and Contributor ID, Inc. (ORCID) as an internationalized resource identifier (IRI) following the defined pa
@apdavison please correct if this suggestion is incorrect

2023-02-28 10:26 UTC, lzehl approved these changes
changed the instructions slightly according to my previous comment

2023-02-28 10:27 UTC, lzehl commented
@Peyman-N or @aeidi89 or @apdavison feel free to merge is you also approve now

2023-02-28 10:34 UTC, aeidi89 approved these changes
Looks good.

2023-02-28 10:36 UTC, merged

2023-02-28 10:36 UTC, Peyman-N approved these changes