Clean up: person
openMetadataInitiative/openMINDS_core pull request #425
Opened 2023-02-13 14:45 UTC by UlrikeS91

MINOR changes:
- improved instructions
- establish alphabetical order

MAJOR changes:
none

SPECIAL ATTENTION:
none

2023-02-20 08:44 UTC, lzehl requested changes

2023-02-20 08:44 UTC, lzehl commented on schemas/actors/person.schema.tpl.json
> +      "_instruction": "Enter all current and, if necessary, past affiliations of this person.",
I would not use "if necessary". Delete this either completely or replace with e.g. "...and (if desired) past ..."

2023-02-28 10:13 UTC, lzehl approved these changes
changed instructions of "affiliation" to "..., if desired, ..."

2023-02-28 10:13 UTC, lzehl commented
@Peyman-N or @apdavison or @aeidi89 feel free to merge if you also approve

2023-02-28 10:16 UTC, Peyman-N approved these changes

2023-02-28 10:17 UTC, merged