Clean up: quantitative value array
openMetadataInitiative/openMINDS_core pull request #431
Opened 2023-02-14 08:47 UTC by UlrikeS91

MINOR changes:
- improved instructions
- establish alphabetical order
- establish correct order within a property

MAJOR changes:
none

SPECIAL ATTENTION:
none

2023-02-20 08:59 UTC, lzehl requested changes

2023-02-20 08:59 UTC, lzehl commented on schemas/miscellaneous/quantitativeValueArray.schema.tpl.json
> +      "_instruction": "Add the type of uncertainty used to determine the uncertainity for this quantitative value array.",
typo "uncertainity" -> "uncertainty" but I also find this sentence a bit weird. I liked the old one better.

2023-02-20 08:59 UTC, lzehl commented on schemas/miscellaneous/quantitativeValueArray.schema.tpl.json
> +      "_instruction": "Add the type of uncertainty used to determine the uncertainity for this quantitative value array.",
Maybe this

"Add the type of uncertainty used to estimate the uncertainties for the array stated under 'values'."

2023-02-20 08:59 UTC, lzehl commented on schemas/miscellaneous/quantitativeValueArray.schema.tpl.json
> +      "_instruction": "Enter an array of negative uncertainties for this quantitative value array. Note that it must have the same length as the array of quantitative values stated under 'values'.",
I think this should not state "quantitative values" since they are defined with this schema. The values under value are only numbers... 

Maybe "Enter an array of negative uncertainties for this quantitative value array. Note that it must have the same length as the array stated under 'values'."

2023-02-20 08:59 UTC, lzehl commented on schemas/miscellaneous/quantitativeValueArray.schema.tpl.json
> +      "_instruction": "Enter an array of positive uncertainties for this quantitative value array. Note that it must have the same length as the array of quantitative values stated under 'values'.",
see above

2023-02-20 08:59 UTC, lzehl commented on schemas/miscellaneous/quantitativeValueArray.schema.tpl.json
> +      "_instruction": "Enter the array of quantitative values.",
see comment above "Enter the array of measured values."

2023-02-20 08:59 UTC, lzehl commented
@Peyman-N or @apdavison I need your input here

2023-02-28 10:05 UTC, lzehl approved these changes
Inspired by the simplification of instructions in #432 I tried to also adapt these instructions.

2023-02-28 10:06 UTC, lzehl commented
@Peyman-N or @apdavison or @aeidi89 please double check and feel free to merge if you approve of the changes

2023-03-06 10:24 UTC, Peyman-N approved these changes

2023-03-06 10:26 UTC, merged