Clean up: quantitative value range
openMetadataInitiative/openMINDS_core pull request #432
Opened 2023-02-14 08:50 UTC by UlrikeS91

MINOR changes:
- improved instructions

MAJOR changes:
none

SPECIAL ATTENTION:
none

2023-02-20 09:02 UTC, lzehl requested changes

2023-02-20 09:02 UTC, lzehl commented on schemas/miscellaneous/quantitativeValueRange.schema.tpl.json
> +      "_instruction": "Enter the maximum value for this quantitative value range."
I think we should not use "quantitative value" here but keep the old phrasing

2023-02-20 09:02 UTC, lzehl commented on schemas/miscellaneous/quantitativeValueRange.schema.tpl.json
> +      "_instruction": "Enter the minimum value for this quantitative value range."
see above

2023-02-20 09:02 UTC, lzehl commented
@apdavison I need your input here

2023-02-27 12:21 UTC, apdavison commented
I don't feel strongly about this. "Enter the maximum value." and "Enter the minimum value." would be sufficiently clear in context.

2023-02-28 09:43 UTC, lzehl approved these changes
changed the instructions to @apdavison suggestion.

2023-02-28 09:44 UTC, lzehl commented
@Peyman-N or @apdavison or @aeidi89 feel free to merge if you also approve now

2023-02-28 12:24 UTC, aeidi89 approved these changes
Looks good.

2023-02-28 12:25 UTC, merged