Clean up: service link
openMetadataInitiative/openMINDS_core pull request #435
Opened 2023-02-14 09:07 UTC by UlrikeS91

MINOR changes:
- improved instructions
- renamed `name` to `displayLabel` since this is what we are actually asking for (which is describe din the instructions)

MAJOR changes:
none

SPECIAL ATTENTION:
- replaced embedded URL for `openDataIn` by IRI; this is the only case were URL is embedded which is not very consistent, IRI achieves almost the same thing and is also "embedded"

2023-02-20 09:07 UTC, lzehl requested changes

2023-02-20 09:07 UTC, lzehl commented on schemas/data/serviceLink.schema.tpl.json
> +      "_instruction": "Add an image (static or moving) to this service link that acts as a preview of its content or could function as an icon.",
"Add a file instance of an image or a small movie for this service link that can act as a preview or function as an icon."

2023-02-28 09:39 UTC, lzehl approved these changes
changed instructions for "previewImage" to "Add an image file to this service link ..." because if this can be a static image or a moving image (e.g. gif) is actually something the database system needs to define.

2023-02-28 09:40 UTC, lzehl commented
@Peyman-N or @apdavison or @aeidi89 feel free to merge if you also approve the changes

2023-02-28 12:21 UTC, aeidi89 approved these changes
This looks good.

2023-02-28 12:21 UTC, merged