Clean up: setup
openMetadataInitiative/openMINDS_core pull request #436
Opened 2023-02-14 09:15 UTC by UlrikeS91

MINOR changes:
- improved instructions
- establish alphabetical order
- fixed indentation
- renamed `setupType` to `type` to reduce list of property names and because we decided to use type when the specific context is explicit

MAJOR changes:
none

SPECIAL ATTENTION:
none

2023-02-14 10:58 UTC, Peyman-N approved these changes

2023-02-20 09:42 UTC, lzehl requested changes

2023-02-20 09:42 UTC, lzehl commented on schemas/products/setup.schema.tpl.json
> +      "_instruction": "Add all components, including other setups, that are part in this setup. The setup must be composed of at least one device.",
this seems like contradiction... minItems 2 but only one device is required according to the instructions...

2023-02-28 09:33 UTC, lzehl requested changes

2023-02-28 09:33 UTC, lzehl commented on schemas/products/setup.schema.tpl.json
> +      "_instruction": "Add all components, including other setups, that are part in this setup. The setup must be composed of at least one device.",
I suggest to just delete the second sentence.

2023-02-28 09:56 UTC, lzehl approved these changes
updated instructions of "components" to "Add all components, including other setups, that are part in this setup. Note that a setup should not be only composed of software."

2023-02-28 09:56 UTC, lzehl commented on schemas/products/setup.schema.tpl.json
> +      "_instruction": "Add all components, including other setups, that are part in this setup. The setup must be composed of at least one device.",
changed to "Add all components, including other setups, that are part in this setup. Note that a setup should not be only composed of software."

2023-02-28 09:57 UTC, merged