adding two LocaliZoom content types
openMetadataInitiative/openMINDS_core pull request #487
Opened 2023-08-28 14:32 UTC by Majpuc

Two new content types are.
-.lz
-.json
Both are in jsonld format

2023-08-29 12:09 UTC, Majpuc commented
Added the QCAlign+JSON jsonld today

2023-08-29 14:30 UTC, lzehl requested changes
@Majpuc you can actually add a short description for each content type (to avoid my questioning and indicate the purpose of the CT for the user). 

Just add a description to the property list (they are alphabetically ordered); example:
`"description": "Files of this content type contain ..."`

2023-08-29 14:30 UTC, lzehl commented on instances/data/contentTypes/vnd.localizoom+json.jsonld
> +    "name": "application/vnd.localizoom+json",
It would be good to indicate the purpose of this file in the naming when these are related to general media types. 

e.g. application/vnd.localizoom.X+json where X could be "transformation", "config", or ? (depending on what is stored, expected in there)

2023-08-29 14:30 UTC, lzehl commented on instances/data/contentTypes/vnd.localizoom.lz.jsonld
> +    "@id": "https://openminds.ebrains.eu/instances/contentTypes/application_vnd.localizoom.lz",
what is in this file contained?

2023-08-29 14:30 UTC, lzehl commented on instances/data/contentTypes/vnd.localizoom+json.jsonld
> +    "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.localizoom+json",
please follow the new convention for the atIDs:

`"@id": "https://openminds.ebrains.eu/instances/contentTypes/application_vnd.localizoom+json"`

2023-08-29 14:30 UTC, lzehl commented on instances/data/contentTypes/vnd.localizoom+json.jsonld
> +    "@id": "https://openminds.ebrains.eu/instances/contentTypes/application/vnd.localizoom+json",
adapt atID in accordance with my second comment

2023-08-30 08:05 UTC, Majpuc commented on instances/data/contentTypes/vnd.localizoom+json.jsonld
> +    "name": "application/vnd.localizoom+json",
After verification, I'll have to retract this one. Not sure how I do this?

2023-08-30 08:08 UTC, Majpuc commented on instances/data/contentTypes/vnd.localizoom.lz.jsonld
> +    "@id": "https://openminds.ebrains.eu/instances/contentTypes/application_vnd.localizoom.lz",
Localizoom parameter file. input and output file for Localizoom webapp.

2023-08-30 08:12 UTC, lzehl commented on instances/data/contentTypes/vnd.localizoom+json.jsonld
> +    "name": "application/vnd.localizoom+json",
just delete the file in the branch from which you are doing your pull request. the PR is automatically updated

2023-08-31 07:46 UTC, lzehl approved these changes

2023-08-31 07:47 UTC, merged