feat: added first iteration of softwareversion
openMetadataInitiative/openMINDS_core pull request #90
Opened 2020-10-16 09:39 UTC by xgui3783

related to #76

2020-10-20 11:13 UTC, xgui3783 commented
Pending discussion from #76

2020-10-22 14:02 UTC, lzehl requested changes

2020-10-22 14:02 UTC, lzehl commented on v3.0/products/softwareversion.schema.json
> +  "$id": "https://schema.ebrains.eu/openminds/softwareversion.schema.json",
please change into .../softwareVersion.schema.json (also for the file name)

2020-10-22 14:02 UTC, lzehl commented on v3.0/products/softwareversion.schema.json
> +  "required": [
"contributors" are missing from the required list

2020-10-22 14:02 UTC, lzehl commented on v3.0/products/softwareversion.schema.json
> +      "description": "Metadata node type (scehma).",
typo -> "Metadata node type (schema)."

2020-10-22 14:02 UTC, lzehl commented on v3.0/products/softwareversion.schema.json
> +      "const": "https://openminds.ebrains.eu/core/modelVersion"
should be ".../softwareVersion"

2020-10-22 14:02 UTC, lzehl commented on v3.0/products/softwareversion.schema.json
> +      "description": ""
"Alternative short name or label."

2020-10-22 14:02 UTC, lzehl commented on v3.0/products/softwareversion.schema.json
> +      "minItems": 1,
not needed for required properties

2020-10-22 14:02 UTC, lzehl commented on v3.0/products/softwareversion.schema.json
> +      "minItems": 1,
not needed for required properties

2020-10-22 14:02 UTC, lzehl commented on v3.0/products/softwareversion.schema.json
> +      "description": "",
`"List of contributors (persons or organizations) and their role they played for generating this research product version."`

2020-10-22 14:02 UTC, lzehl commented on v3.0/products/softwareversion.schema.json
> +      "description": ""
Definition of copyright owner and year for this research product version.

2020-10-22 14:02 UTC, lzehl commented on v3.0/products/softwareversion.schema.json
> +      "minItems": 1,
not needed for required properties

2020-10-22 14:02 UTC, lzehl commented on v3.0/products/softwareversion.schema.json
> +      "minItems": 1,
not needed for required properties

2020-10-22 14:02 UTC, lzehl commented on v3.0/products/softwareversion.schema.json
> +      "minItems": 1,
not needed for required properties

2020-10-22 14:02 UTC, lzehl commented on v3.0/products/softwareversion.schema.json
> +      "minItems": 0,
not needed if not a required property

2020-10-22 14:02 UTC, lzehl commented on v3.0/products/softwareversion.schema.json
> +      "minItems": 0,
not needed if not a required property

2020-10-22 14:02 UTC, lzehl commented on v3.0/products/softwareversion.schema.json
> +      "minItems": 0,
not needed if not a required property

2020-10-22 14:02 UTC, lzehl commented on v3.0/products/softwareversion.schema.json
> +      "minItems": 1,
not needed for required properties

2020-10-22 14:02 UTC, lzehl commented on v3.0/products/softwareversion.schema.json
> +      "minItems": 1,
not needed for required properties

2020-10-22 14:02 UTC, lzehl commented on v3.0/products/softwareversion.schema.json
> +      "minItems": 1,
not needed for required properties

2020-10-22 14:02 UTC, lzehl commented on v3.0/products/softwareversion.schema.json
> +      "minItems": 1,
not needed for required properties

2020-10-22 14:02 UTC, lzehl commented on v3.0/products/softwareversion.schema.json
> +      "minItems": 1,
not needed for required properties

2020-10-22 14:02 UTC, lzehl commented on v3.0/products/softwareversion.schema.json
> +      "minItems": 1,
not needed for required properties

2020-10-22 14:02 UTC, lzehl commented on v3.0/products/softwareversion.schema.json
> +      "minItems": 1,
not needed for required properties

2020-10-22 14:02 UTC, lzehl commented on v3.0/products/softwareVersion.schema.json
> +      "minItems": 1,
not needed because it's not required

2020-10-22 14:02 UTC, lzehl commented on v3.0/products/softwareVersion.schema.json
> +      "minItems": 1,
not needed because it's required

2020-10-22 14:04 UTC, lzehl commented
Could you remove all the `"minItems": 1`? In case the property is required the expected min within json-schema is anyway 1 and in case the property is not required this setting is not needed because the property does not have to be defined.

2020-10-22 15:19 UTC, xgui3783 commented
@lzehl  I thought `required` and `minItems` describe two very different things? 

I though `required` indicates that the property need to exist, but `minItems` dictates the min length of an array. 

For example 

schema.json:
```json
{
  "$schema": "http://json-schema.org/draft-09/schema#",
  "type": "object",
  "required": [
    "exampleArray"
  ],
  "properties": {
    "exampleArray": {
      "type": "array",
      "items": {
      	"type": "string"
      }
    }
  }
}
```

would satisfy

```json
{
  "exampleArray": []
}
```

even though exampleArray is a required property, it can have length 0?

2020-10-22 16:43 UTC, lzehl commented
@xgui3783 you are right (although in our case we use draft-07... I was sure it would not not work that way since the item has to be of type string which it is not if the array is empty... weird... 

@UlrikeS91 this also concerns SANDS and other schemas: could you make a corresponding fix? (see last comment from Xiao)

2020-10-22 16:44 UTC, merged

2020-10-23 10:49 UTC, UlrikeS91 commented
> @xgui3783 you are right (although in our case we use draft-07... I was sure it would not not work that way since the item has to be of type string which it is not if the array is empty... weird...
> 
> @UlrikeS91 this also concerns SANDS and other schemas: could you make a corresponding fix? (see last comment from Xiao)

I checked for draft-07 and it basically says what @xgui3783 explained (with draft-09): An empty array is always valid. So, we need to specific `minItem` each time. We could in fact push this even further, and discuss `uniqueItems` as well: The default is false. The best worst-case example is `laterality` (in SANDS `annotation`). We defined `maxItem` as 2, but since they don't have to be unique, I could add the same `controlledTerm` twice. This could otherwise also be a good tool in cases where the items really need to be unique, e.g. contribuotrs to a `datasetVersion`.

2020-10-26 08:20 UTC, lzehl commented
@UlrikeS91 yes! this is indeed true. Could you make a corresponding PR (this does not have to include everything already but the obvious cases would be good)?

2020-10-26 08:25 UTC, UlrikeS91 commented
> @UlrikeS91 yes! this is indeed true. Could you make a corresponding PR (this does not have to include everything already but the obvious cases would be good)?

I can do that (hopefully by the end of today even).