Create organization schema
openMetadataInitiative/openMINDS_core pull request #94
Opened 2020-10-20 11:09 UTC by skoehnen

Related to #84

2020-10-20 12:02 UTC, skoehnen reviewed
The required property is still missing

2020-10-20 12:02 UTC, skoehnen commented on v3.0/products/organization.schema.json
> +      "description": "???",
I am not sure what a good description would be here.
@UlrikeS91 @lzehl maybe you have some good suggestions.

What would the digitalIdentifier of an organization be?

2020-10-20 12:17 UTC, apdavison commented on v3.0/products/organization.schema.json
> +      "description": "???",
Maybe take a look at https://ror.org and https://www.grid.ac ?

2020-10-20 12:21 UTC, apdavison commented on v3.0/products/organization.schema.json
> +      "description": "???",
ROR (e.g. https://ror.org/02nv7yv05) looks like the best. More information at https://scholarlykitchen.sspnet.org/2019/12/04/are-you-ready-to-ror-an-inside-look-at-this-new-organization-identifier-registry/

2020-10-21 08:05 UTC, skoehnen commented on v3.0/products/organization.schema.json
> +      "description": "???",
Ah interesting.
I wasn't aware of those registrars

But that makes sense to me.
I will set the format of the string to URI.

2020-10-21 09:29 UTC, lzehl reviewed
required properties you did add later if I remember correctly.

2020-10-21 09:29 UTC, lzehl commented on v3.0/products/organization.schema.json
> +      "const": "https://openminds.ebrains.eu/core/datasetVersion"
this needs to be ".../core/organization"

2020-10-21 09:29 UTC, lzehl commented on v3.0/products/organization.schema.json
> +      "description": "???",
Globally unique and (best) persistent digital identifier for the organization.

2020-10-21 09:29 UTC, lzehl commented on v3.0/products/organization.schema.json
> +      "description": "???",
I agree with  @apdavison here, ROR should be preferred but we will not limit it to this

2020-10-21 09:35 UTC, lzehl requested changes
- `@type` needs to be corrected
- `globalIdentifier` `description` : I made a different suggestion

2020-10-21 09:36 UTC, lzehl commented
@skoehnen I think Ulrike's review is not needed in addition. @UlrikeS91 hope you agree.

2020-10-21 09:46 UTC, skoehnen commented
> @skoehnen I think Ulrike's review is not needed in addition. @UlrikeS91 hope you agree.

Hi, I added both of you so you know that someone can review it.
When we started with this we agreed that it is okay if one of us reviews the pull requests and I was still working under this assumption.
If that changed in the meantime, I will change how I set up the Pull Requests?

2020-10-21 09:48 UTC, skoehnen commented on v3.0/products/organization.schema.json
> +      "description": "???",
> Globally unique and (best) persistent digital identifier for the organization.

What do you mean with best in this case?
The best identifier or the identifier should better be persistent.

In either case I would remove `(best)`

2020-10-21 09:49 UTC, skoehnen commented on v3.0/products/organization.schema.json
> +      "const": "https://openminds.ebrains.eu/core/datasetVersion"
Oh yes, you are totally correct.

2020-10-21 09:51 UTC, skoehnen commented on v3.0/products/organization.schema.json
> +      "const": "https://openminds.ebrains.eu/core/datasetVersion"
Is fixed.

2020-10-21 09:54 UTC, skoehnen commented
> Required properties are okay for now. The globalIdentifier should be highly recommended, though.

Yes I agree, sadly we only have required 😅 
And I think to require to would maybe a bit too strict and cause problems.

2020-10-21 09:58 UTC, skoehnen commented
> * `globalIdentifier` `description` : I made a different suggestion

You called the digitalIdentifier globalIdentifier a few times now.
Should we change the name.

(I had to check #84 to make sure I didn't make an error in the first place 😅)

2020-10-21 10:00 UTC, skoehnen commented on v3.0/products/organization.schema.json
> +      "description": "???",
@lzehl I updated the description if you want to take a look.

2020-10-21 10:51 UTC, lzehl commented
@skoehnen so sorry :see_no_evil: the property is still called `digitalIdentifier`... I just always confuse it... In principle they identifiers there should be all globally unique, so we could also call the property `globalIdentifier` but I wasn't sure if "global" is really always the case.

2020-10-21 11:45 UTC, skoehnen commented
> @skoehnen so sorry 🙈 the property is still called `digitalIdentifier`... I just always confuse it... In principle they identifiers should be all globally unique, so we could also call the property `globalIdentifier` but I wasn't sure if "global" is really always true for all the cases this property (and corresponding schema) is used.

Okay 👍
Just wanted to make sure

2020-10-23 10:11 UTC, UlrikeS91 approved these changes

2020-10-23 10:11 UTC, UlrikeS91 commented
@skoehnen and @lzehl, Is there anything I need to do here? Based on the comments:

1) Yes, I agree. Only one review should be enough. So, whenever Lyuba reviews, I don't need to review as well. I also got it like Stefan explained it, and if that changed, I also didn't get that message, @skoehnen :D

2) I reviewed it anyway to see if something was missing (which would explain why the schema isn't merge into the master yet), but it looks good to me. Stefan change the description as requested by Lyuba. @lzehl, Do you agree that we should merge this now?

2020-10-26 08:27 UTC, lzehl commented
@UlrikeS91 yes go ahead and merge it :+1:

2020-10-26 08:27 UTC, lzehl approved these changes

2020-10-26 08:38 UTC, merged